# Generated by Django 3.2.18 on 2023-03-15 05:48

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('nesting', models.CharField(max_length=128)),
                ('new_code', models.CharField(blank=True, max_length=255, null=True)),
                ('display_observation', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='BeachPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('new_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EntryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('pr_date_convention', models.BooleanField(db_column='PR_DATE_CONVENTION')),
                ('entered_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entry batches',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('rookery', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], max_length=1, null=True)),
                ('beach_approach', models.CharField(blank=True, max_length=50, null=True)),
                ('aspect', models.CharField(blank=True, max_length=3, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('comments', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='turtle_tag.location')),
            ],
        ),
        migrations.CreateModel(
            name='TagStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Turtle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_confidence', models.CharField(blank=True, max_length=1, null=True)),
                ('sex', models.CharField(max_length=1)),
                ('cause_of_death', models.CharField(blank=True, choices=[('BS', 'Boat strike'), ('DR', 'Drowning'), ('FI', 'Fishery'), ('HA', 'Handling accident'), ('IH', 'Indigenous hunt'), ('MO', 'Misorientation on beach'), ('NC', 'Natural causes'), ('SH', 'Shark predation'), ('UK', 'Unknown')], max_length=2, null=True)),
                ('re_entered_population', models.CharField(blank=True, max_length=1, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entered_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_entered', models.DateTimeField(blank=True, null=True)),
                ('original_turtle_id', models.IntegerField(blank=True, null=True)),
                ('entry_batch_id', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('mund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turtle_tag.location')),
            ],
        ),
        migrations.CreateModel(
            name='TurtleSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=128, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=128, null=True)),
                ('old_species_code', models.CharField(blank=True, max_length=2, null=True)),
                ('hide_dataentry', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TurtleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('new_tag_list', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TurtleObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('observation_date_old', models.DateTimeField(blank=True, null=True)),
                ('alive', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], max_length=1, null=True)),
                ('place_description', models.CharField(blank=True, max_length=300, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('nesting', models.BooleanField(null=True)),
                ('clutch_completed', models.CharField(blank=True, max_length=1, null=True)),
                ('number_of_eggs', models.SmallIntegerField(blank=True, null=True)),
                ('egg_count_method', models.CharField(blank=True, choices=[('1Dr', 'Obs drop on laying'), ('2Ex', 'Exc & count post-lay'), ('3PH', 'Post-hatch nest exhumation')], max_length=3, null=True)),
                ('measurements', models.CharField(max_length=1)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entered_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_entered', models.DateField(blank=True, null=True)),
                ('original_observation_id', models.IntegerField(blank=True, null=True)),
                ('comment_fromrecordedtagstable', models.TextField(blank=True, null=True)),
                ('scars_left', models.BooleanField()),
                ('scars_right', models.BooleanField()),
                ('other_tags', models.TextField(blank=True, null=True)),
                ('other_tags_identification_type', models.CharField(blank=True, choices=[('A', 'Qld - monel A series tag'), ('Acoustic', 'Acoustic'), ('ATLANTIS', 'Atlantis [now closed]'), ('CA', 'CofAust - titanium tag'), ('CT', 'Cayman - juvenile tag'), ('CTD', 'Conductivity - Temp - Depth SRDL'), ('ENT/REL', 'Untagged turtle - live release from entanglement'), ('ENT/SAL', 'Untagged turtle - salvage from entanglement'), ('FISH/DECD', 'Untagged turtle - Fishery capture victim'), ('FREE/OBS', 'Untagged turtle - live obs'), ('I', 'HIMB - Inconel tag'), ('K', 'Qld - titanium K series tag'), ('PTT', 'PT transmitter'), ('PZ ID', 'Perth Zoo Vets - case ID'), ('RREC', 'Naragebup rehab'), ('SFU/FIU', 'RotoTag'), ('SRDL', 'Satellite Relay Data Logger (SRDL)/?CATS-SATags'), ('STRAND/SAL', 'Untagged turtle - stranding victim'), ('T', 'Qld - titanium T series tag'), ('UWW', 'Underwater World [now AQWA]'), ('WAMusR', 'WA Museum R#')], max_length=10, null=True)),
                ('transferid', models.IntegerField(blank=True, null=True)),
                ('mund', models.BooleanField()),
                ('scars_left_scale_1', models.BooleanField()),
                ('scars_left_scale_2', models.BooleanField()),
                ('scars_left_scale_3', models.BooleanField()),
                ('scars_right_scale_1', models.BooleanField()),
                ('scars_right_scale_2', models.BooleanField()),
                ('scars_right_scale_3', models.BooleanField()),
                ('cc_length_not_measured', models.BooleanField()),
                ('cc_notch_length_not_measured', models.BooleanField()),
                ('cc_width_not_measured', models.BooleanField()),
                ('tagscarnotchecked', models.BooleanField()),
                ('didnotcheckforinjury', models.BooleanField()),
                ('date_convention', models.CharField(max_length=1)),
                ('observation_status', models.CharField(blank=True, max_length=128, null=True)),
                ('corrected_date', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.activity')),
                ('beach_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.beachposition')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.condition')),
                ('entered_by_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_by', to=settings.AUTH_USER_MODEL)),
                ('entry_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.entrybatch')),
                ('measurer_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurer', to=settings.AUTH_USER_MODEL)),
                ('measurer_reporter_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurer_reporter', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.place')),
                ('reporter_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter', to=settings.AUTH_USER_MODEL)),
                ('tagger_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagger', to=settings.AUTH_USER_MODEL)),
                ('turtle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.turtle')),
            ],
        ),
        migrations.AddField(
            model_name='turtle',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turtle_tag.turtlespecies'),
        ),
        migrations.AddField(
            model_name='turtle',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turtle_tag.turtlestatus'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_order_id', models.IntegerField(blank=True, null=True)),
                ('issue_location', models.CharField(blank=True, max_length=50, null=True)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('custodian_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian', to=settings.AUTH_USER_MODEL)),
                ('field_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field', to=settings.AUTH_USER_MODEL)),
                ('tag_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.tagstatus')),
                ('turtle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='turtle_tag.turtle')),
            ],
        ),
        migrations.CreateModel(
            name='PitTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_location', models.CharField(blank=True, max_length=50, null=True)),
                ('pit_tag_status', models.CharField(blank=True, max_length=10, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('tag_order_id', models.IntegerField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('box_number', models.CharField(blank=True, max_length=50, null=True)),
                ('custodian_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_person', to=settings.AUTH_USER_MODEL)),
                ('field_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_person', to=settings.AUTH_USER_MODEL)),
                ('turtle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pit_tags', to='turtle_tag.turtle')),
            ],
        ),
    ]
