# Generated by Django 3.2.18 on 2023-03-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_tag', '0002_auto_20230329_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('minimum_value', models.FloatField(blank=True, null=True)),
                ('maximum_value', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.measurementtype')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turtle_tag.turtleobservation')),
            ],
            options={
                'unique_together': {('observation', 'measurement_type')},
            },
        ),
    ]
