# Generated by Django 3.2.18 on 2023-03-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_tag', '0003_measurement_measurementtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtleobservation',
            name='date_entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='TurtleDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('A', 'Carapace - entire'), ('B', 'Left front flipper'), ('C', 'Right front flipper'), ('D', 'Left rear flipper'), ('E', 'Right rear flipper'), ('H', 'Head'), ('I', 'Center mid-carapace'), ('J', 'Right front carapace'), ('K', 'Left front carapace'), ('L', 'Left rear carapace'), ('M', 'Right rear carapace'), ('N', 'Front mid-carapace'), ('O', 'Rear mid-carapace'), ('P', 'Plastron - entire'), ('T', 'Tail'), ('W', 'Whole animal')], max_length=4)),
                ('damage', models.CharField(choices=[('0', 'None significant'), ('1', 'Tip off - Flipper'), ('2', 'Lost from Nail - Flipper'), ('3', 'Lost half - Flipper'), ('4', 'Lost whole - Flipper'), ('5', 'Minor Wounds or cuts'), ('6', 'Major Wounds or cuts'), ('7', 'Deformity')], max_length=4)),
                ('cause', models.CharField(blank=True, choices=[('AG', 'Thick algae'), ('BB', 'Barnacles'), ('BP', 'Bite from predator'), ('BT', 'Bite from turtle'), ('MM', 'Thick mud'), ('OI', 'Other Impact'), ('PS', 'Parasites (other than barnacles)'), ('SD', 'Strike damage')], max_length=4, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage', to='turtle_tag.turtleobservation')),
            ],
        ),
    ]
