# Generated by Django 3.2.18 on 2023-03-31 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_tag', '0005_turtletagobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurtlePitTagObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('A1', 'Applied new - Read OK'), ('AE', 'Applied new - Did not read'), ('N', 'Not Recorded'), ('P', 'Present Obs - & Read OK'), ('P_OK', 'Present Obs - OK fix & Read'), ('PX', 'Present Obs - Tag#s not read'), ('RQ', 'Insecure at Obs - Action ??')], max_length=8, null=True)),
                ('position', models.CharField(blank=True, choices=[('A1', 'Applied new - Read OK'), ('AE', 'Applied new - Did not read'), ('N', 'Not Recorded'), ('P', 'Present Obs - & Read OK'), ('P_OK', 'Present Obs - OK fix & Read'), ('PX', 'Present Obs - Tag#s not read'), ('RQ', 'Insecure at Obs - Action ??')], max_length=8, null=True)),
                ('checked', models.BooleanField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pit_tag_observations', to='turtle_tag.turtleobservation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='turtle_tag.turtlepittag')),
            ],
        ),
    ]
