# Generated by Django 3.2.18 on 2023-04-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_tag', '0006_turtlepittagobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtle',
            name='date_entered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turtle',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown'), ('I', 'Indeterminate')], max_length=1),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='clutch_completed',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Possible'), ('U', 'Uncertain'), ('D', "Didn't check")], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='date_entered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='observation_status',
            field=models.CharField(blank=True, choices=[('Initial Nesting', 'Initial Nesting'), ('Initial Sighting', 'Initial Sighting'), ('Remigrant', 'Remigrant'), ('Resighting', 'Resighting')], max_length=128, null=True),
        ),
    ]
