# Generated by Django 3.2.18 on 2023-04-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_tag', '0007_auto_20230404_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turtleobservation',
            old_name='observation_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='date_convention',
            field=models.CharField(choices=[('C', 'Calendar'), ('E', 'Evening'), ('U', 'Unknown')], max_length=1),
        ),
    ]
