# Generated by Django 3.2.18 on 2023-04-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_tag', '0008_auto_20230404_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='display_observation',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entrybatch',
            name='pr_date_convention',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtle',
            name='date_entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='cc_length_not_measured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='cc_notch_length_not_measured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='cc_width_not_measured',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='date_entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='didnotcheckforinjury',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='mund',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='scars_left',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='scars_left_scale_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='scars_left_scale_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='scars_left_scale_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='scars_right',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='scars_right_scale_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='scars_right_scale_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='scars_right_scale_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='tagscarnotchecked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtlepittagobservation',
            name='checked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtlespecies',
            name='hide_dataentry',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtlestatus',
            name='new_tag_list',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='turtletagobservation',
            name='barnacles',
            field=models.BooleanField(null=True),
        ),
    ]
