apiVersion: batch/v1
kind: CronJob
metadata:
  name: turtles-cronjob
spec:
  # 12:30 daily (AWST -> UTC)
  schedule: '30 4 * * *'
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: turtles-cronjob
              args: ['manage.py', 'automated_qa_checks']
              envFrom:
                - secretRef:
                    name: turtles-env-uat
