# Generated by Django 2.1.5 on 2019-02-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20180926_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlenestobservation',
            name='comments',
            field=models.TextField(blank=True, help_text='Any other comments or notes.', null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='turtlenestobservation',
            name='no_live_hatchlings_neck_of_nest',
            field=models.PositiveIntegerField(blank=True, help_text='The number of live hatchlings in the neck of the nest.', null=True, verbose_name='Live hatchlings in neck of nest'),
        ),
    ]
