# Generated by Django 3.2.20 on 2023-07-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20230710_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperatureloggerdeployment',
            name='observation_ptr',
        ),
        migrations.RemoveField(
            model_name='temperatureloggersettings',
            name='observation_ptr',
        ),
        migrations.AlterField(
            model_name='lightsourceobservation',
            name='light_source_type',
            field=models.CharField(choices=[('na', 'NA'), ('natural', 'Natural'), ('artificial', 'Artificial')], default='na', max_length=300, verbose_name='Light source type'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='cloud_cover_at_emergence_known',
            field=models.CharField(choices=[('na', 'NA'), ('yes', 'Yes'), ('no', 'No')], default='na', max_length=300, verbose_name='Cloud cover at emergence known'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='hatchling_emergence_time_accuracy',
            field=models.CharField(blank=True, choices=[('na', 'NA'), ('same-night', 'Sometime that night'), ('plusminus-2h', 'Plus/minus 2h of estimate'), ('plusminus-30m', 'Correct to the hour')], default='na', max_length=300, null=True, verbose_name='Hatchling emergence time estimate accuracy'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='hatchling_emergence_time_known',
            field=models.CharField(choices=[('na', 'NA'), ('yes', 'Yes'), ('no', 'No')], default='na', max_length=300, verbose_name='Hatchling emergence time known'),
        ),
        migrations.DeleteModel(
            name='DispatchRecord',
        ),
        migrations.DeleteModel(
            name='TemperatureLoggerDeployment',
        ),
        migrations.DeleteModel(
            name='TemperatureLoggerSettings',
        ),
    ]
