# Generated by Django 3.2.20 on 2023-07-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_auto_20230718_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DugongMorphometricObservation',
        ),
    ]
