# Generated by Django 3.2.20 on 2023-08-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_delete_dugongmorphometricobservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turtlehatchlingemergenceobservation',
            name='hatchling_path_to_sea',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(blank=True, choices=[('stranding', 'Stranding'), ('tagging', 'Tagging'), ('nest', 'Nest'), ('tracks', 'Tracks'), ('inwater', 'In water'), ('tag-management', 'Tag Management'), ('logger', 'Logger'), ('other', 'Other')], default='other', editable=False, help_text='The primary concern of this encounter.', max_length=300, null=True, verbose_name='Encounter type'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct entry'), ('paper', 'Paper data sheet'), ('odk', 'OpenDataKit mobile data capture'), ('wamtram', 'WAMTRAM 2 tagging DB'), ('ntp-exmouth', 'NTP Access DB Exmouth'), ('ntp-broome', 'NTP Access DB Broome'), ('cet', 'Cetacean strandings DB'), ('pin', 'Pinniped strandings DB'), ('reconstructed', 'Reconstructed automatically')], db_index=True, default='direct', help_text='Where was this record captured initially?', max_length=300, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='nesttagobservation',
            name='status',
            field=models.CharField(choices=[('applied-new', 'Applied new'), ('resighted', 'Re-sighted associated with nest')], default='resighted', help_text='The status this tag was seen in, or brought into.', max_length=300, verbose_name='Tag status'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct entry'), ('paper', 'Paper data sheet'), ('odk', 'OpenDataKit mobile data capture'), ('wamtram', 'WAMTRAM 2 tagging DB'), ('ntp-exmouth', 'NTP Access DB Exmouth'), ('ntp-broome', 'NTP Access DB Broome'), ('cet', 'Cetacean strandings DB'), ('pin', 'Pinniped strandings DB'), ('reconstructed', 'Reconstructed automatically')], default='direct', help_text='Where was this record captured initially?', max_length=300, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='surveyend',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct entry'), ('paper', 'Paper data sheet'), ('odk', 'OpenDataKit mobile data capture'), ('wamtram', 'WAMTRAM 2 tagging DB'), ('ntp-exmouth', 'NTP Access DB Exmouth'), ('ntp-broome', 'NTP Access DB Broome'), ('cet', 'Cetacean strandings DB'), ('pin', 'Pinniped strandings DB'), ('reconstructed', 'Reconstructed automatically')], default='direct', help_text='Where was this record captured initially?', max_length=300, verbose_name='Data Source'),
        ),
        migrations.DeleteModel(
            name='PathToSea',
        ),
    ]
