# Generated by Django 3.2.21 on 2023-11-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_auto_20230927_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(blank=True, choices=[('stranding', 'Stranding'), ('tagging', 'Tagging'), ('nest', 'Nest'), ('tracks', 'Tracks'), ('inwater', 'In water'), ('tag-management', 'Tag Management'), ('logger', 'Logger'), ('other', 'Other')], default='other', help_text='The primary concern of this encounter.', max_length=300, null=True),
        ),
    ]
