# Generated by Django 4.2.11 on 2024-04-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0014_alter_observation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisturbanceObservation",
            fields=[
                (
                    "observation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="observations.observation",
                    ),
                ),
                (
                    "disturbance_cause",
                    models.CharField(
                        choices=[
                            ("turtle", "Other turtle"),
                            ("bandicoot", "Bandicoot predation"),
                            ("bird", "Bird predation"),
                            ("cat", "Cat predation"),
                            ("crab", "Crab predation"),
                            ("croc", "Croc predation"),
                            ("cyclone", "Cyclone disturbance"),
                            ("dingo", "Dingo predation"),
                            ("dog", "Dog predation"),
                            ("fox", "Fox predation"),
                            ("goanna", "Goanna predation"),
                            ("human", "Human"),
                            ("pig", "Pig predation"),
                            ("tide", "Tidal disturbance"),
                            ("vehicle", "Vehicle damage"),
                            ("unknown", "Unknown"),
                            ("other", "Other identifiable (see comments)"),
                        ],
                        help_text="The cause of the disturbance.",
                        max_length=300,
                    ),
                ),
                (
                    "disturbance_cause_confidence",
                    models.CharField(
                        choices=[
                            ("na", "Not applicable"),
                            ("guess", "Guess based on insufficient evidence"),
                            ("certain", "Certainty based on local evidence"),
                            (
                                "expert-opinion",
                                "Expert opinion based on available evidence",
                            ),
                            ("validated", "Validated by authoritative source"),
                        ],
                        default="na",
                        help_text="What is the choice of disturbance cause based on?",
                        max_length=300,
                        verbose_name="Disturbance cause choice confidence",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Any other comments or notes.", null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("observations.observation",),
        ),
        migrations.AlterField(
            model_name="animalencounter",
            name="checked_for_flipper_tags",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Was the animal checked for flipper tags, were any found?",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="animalencounter",
            name="checked_for_injuries",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Was the animal checked for injuries, were any found?",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="animalencounter",
            name="nesting_disturbed",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Was the nesting interrupted? If so, specify disturbance in comments.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="animalencounter",
            name="scanned_for_pit_tags",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Was the animal scanned for PIT tags, were any found?",
                max_length=300,
                verbose_name="Scanned for PIT tags",
            ),
        ),
        migrations.AlterField(
            model_name="encounter",
            name="encounter_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stranding", "Stranding"),
                    ("tagging", "Tagging"),
                    ("nest", "Nest"),
                    ("tracks", "Tracks"),
                    ("inwater", "In water"),
                    ("tag-management", "Tag management"),
                    ("logger", "Logger"),
                    ("disturbance", "Disturbance/predator"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="The primary concern of this encounter.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="turtlehatchlingemergenceobservation",
            name="light_sources_present",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                max_length=300,
                verbose_name="Light sources present during emergence",
            ),
        ),
        migrations.AlterField(
            model_name="turtlehatchlingemergenceobservation",
            name="outlier_tracks_present",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="turtlenestdisturbanceobservation",
            name="disturbance_cause",
            field=models.CharField(
                choices=[
                    ("turtle", "Other turtle"),
                    ("bandicoot", "Bandicoot predation"),
                    ("bird", "Bird predation"),
                    ("cat", "Cat predation"),
                    ("crab", "Crab predation"),
                    ("croc", "Croc predation"),
                    ("cyclone", "Cyclone disturbance"),
                    ("dingo", "Dingo predation"),
                    ("dog", "Dog predation"),
                    ("fox", "Fox predation"),
                    ("goanna", "Goanna predation"),
                    ("human", "Human"),
                    ("pig", "Pig predation"),
                    ("tide", "Tidal disturbance"),
                    ("vehicle", "Vehicle damage"),
                    ("unknown", "Unknown"),
                    ("other", "Other identifiable (see comments)"),
                ],
                help_text="The cause of the disturbance.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="turtlenestdisturbancetallyobservation",
            name="disturbance_cause",
            field=models.CharField(
                choices=[
                    ("turtle", "Other turtle"),
                    ("bandicoot", "Bandicoot predation"),
                    ("bird", "Bird predation"),
                    ("cat", "Cat predation"),
                    ("crab", "Crab predation"),
                    ("croc", "Croc predation"),
                    ("cyclone", "Cyclone disturbance"),
                    ("dingo", "Dingo predation"),
                    ("dog", "Dog predation"),
                    ("fox", "Fox predation"),
                    ("goanna", "Goanna predation"),
                    ("human", "Human"),
                    ("pig", "Pig predation"),
                    ("tide", "Tidal disturbance"),
                    ("vehicle", "Vehicle damage"),
                    ("unknown", "Unknown"),
                    ("other", "Other identifiable (see comments)"),
                ],
                default="unknown",
                help_text="The cause of the disturbance.",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="turtlenestencounter",
            name="disturbance",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Is there evidence of predation or other disturbance?",
                max_length=300,
                verbose_name="Evidence of predation or disturbance",
            ),
        ),
        migrations.AlterField(
            model_name="turtlenestencounter",
            name="eggs_counted",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Was the nest excavated and were turtle eggs counted?",
                max_length=300,
                verbose_name="Nest excavated and eggs counted",
            ),
        ),
        migrations.AlterField(
            model_name="turtlenestencounter",
            name="fan_angles_measured",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Were hatchling emergence track fan angles recorded?",
                max_length=300,
                verbose_name="Hatchling emergence recorded",
            ),
        ),
        migrations.AlterField(
            model_name="turtlenestencounter",
            name="hatchlings_measured",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Were turtle hatchlings encountered and their morphometrics measured?",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="turtlenestencounter",
            name="logger_found",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Was a data logger deployed, retrieved, or otherwise encountered?",
                max_length=300,
                verbose_name="Logger present",
            ),
        ),
        migrations.AlterField(
            model_name="turtlenestencounter",
            name="nest_tagged",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("na", "NA (not applicable)")],
                default="na",
                help_text="Was a nest tag applied, re-sighted, or otherwise encountered?",
                max_length=300,
                verbose_name="Nest tag present",
            ),
        ),
    ]
