# Generated by Django 5.2.15 on 2026-06-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0015_disturbanceobservation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalencounter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disturbanceobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hatchlingmorphometricobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lightsourceobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='linetransectencounter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loggerobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='managementaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mediaattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nesttagobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tagobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tissuesampleobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tracktallyobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtledamageobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtlehatchlingemergenceobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtlehatchlingemergenceoutlierobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtlemorphometricobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtlenestdisturbanceobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtlenestdisturbancetallyobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtlenestencounter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtlenestobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turtletrackobservation',
            options={},
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='nest_age',
            field=models.CharField(choices=[('fresh', 'Fresh, made last night'), ('missed', 'Missed turtle, made within past hours'), ('old', 'Old, made before last night'), ('unknown', 'Unknown age')], default='fresh', help_text='The track or nest age.', max_length=300, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='turtlenestencounter',
            name='nest_age',
            field=models.CharField(choices=[('fresh', 'Fresh, made last night'), ('missed', 'Missed turtle, made within past hours'), ('old', 'Old, made before last night'), ('unknown', 'Unknown age')], default='fresh', help_text='The track or nest age.', max_length=300, verbose_name='Age'),
        ),
    ]
