# Generated by Django 3.0.8 on 2020-08-11 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0027_auto_20200805_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_location_accuracy_m',
            field=models.FloatField(blank=True, help_text='The accuracy of the supplied end location in metres, if given.', null=True, verbose_name='End location accuracy (m)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_location_accuracy_m',
            field=models.FloatField(blank=True, help_text='The accuracy of the supplied start location in metres, if given.', null=True, verbose_name='Start location accuracy (m)'),
        ),
    ]
