# Generated by Django 3.1.12 on 2021-09-04 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0035_auto_20210329_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'get_latest_by': 'when', 'ordering': ['-when', 'where'], 'verbose_name': 'Encounter', 'verbose_name_plural': 'Encounters'},
        ),
        migrations.AlterField(
            model_name='observation',
            name='source_id',
            field=models.CharField(default=uuid.UUID('b48e58a0-0d41-11ec-8643-236cfd4bc498'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='surveymediaattachment',
            name='source_id',
            field=models.CharField(default=uuid.UUID('b48e58a0-0d41-11ec-8643-236cfd4bc498'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbanceobservation',
            name='disturbance_cause',
            field=models.CharField(choices=[('turtle', '(A)nother turtle'), ('bandicoot', '(Ba)ndicoot predation'), ('bird', '(Bi)rd predation'), ('crab', '(Cr)ab predation'), ('croc', '(Cr)oc predation'), ('cyclone', '(Cy)clone disturbance'), ('dingo', '(Di)ngo predation'), ('dog', '(Do)g predation'), ('cat', '(Ca)t predation'), ('fox', '(F)ox predation'), ('goanna', '(G)oanna predation'), ('human', '(Hu)man'), ('pig', '(P)ig predation'), ('tide', '(Ti)dal disturbance'), ('vehicle', '(V)ehicle damage'), ('unknown', '(U)nknown'), ('other', '(O)ther identifiable (see comments)'), ('test', 'Training or test record')], help_text='The cause of the disturbance.', max_length=300, verbose_name='Disturbance cause'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbancetallyobservation',
            name='disturbance_cause',
            field=models.CharField(choices=[('turtle', '(A)nother turtle'), ('bandicoot', '(Ba)ndicoot predation'), ('bird', '(Bi)rd predation'), ('crab', '(Cr)ab predation'), ('croc', '(Cr)oc predation'), ('cyclone', '(Cy)clone disturbance'), ('dingo', '(Di)ngo predation'), ('dog', '(Do)g predation'), ('cat', '(Ca)t predation'), ('fox', '(F)ox predation'), ('goanna', '(G)oanna predation'), ('human', '(Hu)man'), ('pig', '(P)ig predation'), ('tide', '(Ti)dal disturbance'), ('vehicle', '(V)ehicle damage'), ('unknown', '(U)nknown'), ('other', '(O)ther identifiable (see comments)'), ('test', 'Training or test record')], default='turtle', help_text='The cause of the disturbance.', max_length=300, verbose_name='Disturbance cause'),
        ),
    ]
