# Generated by Django 3.1.13 on 2021-11-25 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0039_auto_20211022_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='name',
            field=models.CharField(blank=True, editable=False, help_text="An automatically inferred read-only identifier for the encountered subject, e.g. in the case of AnimalEncounters, the animal's earliest associated tag ID. Encounters with the same identifer are encounters of the same subject (e.g. the same turtle).", max_length=1000, null=True, verbose_name='Encounter Subject Identifer'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='source_id',
            field=models.CharField(default=uuid.uuid4, help_text='The ID of the record in the original source, if available, or a randomly generated UUID4.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='surveymediaattachment',
            name='source_id',
            field=models.CharField(default=uuid.uuid4, help_text='The ID of the record in the original source, if available, or a randomly generated UUID4.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
    ]
