# Generated by Django 3.1.14 on 2022-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0043_auto_20220323_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalencounter',
            name='datetime_of_last_sighting',
            field=models.DateTimeField(blank=True, help_text="The observation datetime of this animal's last sighting, shown as local time (no daylight savings), stored as UTC. Blank if the animal has never been seen before.", null=True, verbose_name='Last seen on'),
        ),
    ]
