# Generated by Django 3.2.13 on 2022-05-05 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220505_1107'),
        ('observations', '0045_auto_20220408_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='finished_on',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='site',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='started_on',
        ),
        migrations.AddField(
            model_name='encounter',
            name='expedition',
            field=models.ForeignKey(blank=True, help_text='The Expedition during which this encounter happened, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.expedition', verbose_name='Expedition'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='area',
            field=models.ForeignKey(blank=True, help_text='The entire surveyed area.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.area', verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='The Expedition end, shown as local time (no daylight savings), stored as UTC.', null=True, verbose_name='Expedition end'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The organisation that ran this Expedition owns all records (Surveys and Encounters).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organisation', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='The Expedition start, shown as local time (no daylight savings), stored as UTC.', null=True, verbose_name='Expedition start'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='viewers',
            field=models.ManyToManyField(blank=True, help_text="The nominated organisations are able to view the Expedition's records.", related_name='shared_expeditions', to='users.Organisation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='expedition',
            field=models.ForeignKey(blank=True, help_text='The linked Expedition.', null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.expedition', verbose_name='Expedition'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='expedition_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='sighting_status',
            field=models.CharField(choices=[('na', 'Unidentified'), ('new', 'Initial sighting'), ('resighting', 'Resighting'), ('remigrant', 'Remigrant')], default='na', help_text='The status is inferred automatically based on whether and where this animal was processed and identified last.', max_length=300, verbose_name='Sighting status'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments about the Expedition.', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='fieldmediaattachment',
            name='expedition',
            field=models.ForeignKey(blank=True, help_text='The linked Expedition.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.expedition', verbose_name='Expedition'),
        ),
                migrations.AlterModelOptions(
            name='expedition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitevisit',
            options={},
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='SiteVisit',
        ),

    ]
