# Generated by Django 3.2.13 on 2022-05-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220505_1107'),
        ('observations', '0047_auto_20220512_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='area',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='owner',
        ),
        migrations.AddField(
            model_name='expedition',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='The surveyed Locality.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='observations.area', verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='instigator',
            field=models.ForeignKey(blank=True, help_text='The organisation that ran this Expedition owns all records (Surveys and Encounters).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organisation', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
    ]
