# Generated by Django 3.2.13 on 2022-05-26 01:48

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0049_auto_20220525_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMediaAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('data_sheet', 'Data sheet'), ('journal', 'Field journal'), ('communication', 'Communication record'), ('photograph', 'Photograph'), ('other', 'Other')], default='photograph', help_text='What is the attached file about?', max_length=300, verbose_name='Attachment type')),
                ('title', models.CharField(blank=True, help_text='Give the attachment a representative name', max_length=300, null=True, verbose_name='Attachment name')),
                ('attachment', models.FileField(help_text='Upload the file', max_length=500, upload_to=observations.models.campaign_media, verbose_name='File attachment')),
                ('campaign', models.ForeignKey(blank=True, help_text='The linked Campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.campaign', verbose_name='Campaign')),
            ],
        ),
        migrations.RemoveField(
            model_name='fieldmediaattachment',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='expedition',
        ),
        migrations.AddField(
            model_name='encounter',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The overarching Campaign instigating this Encounter is automatically linked when an Encounter or a Campaign are saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.campaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='survey',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The overarching Campaign instigating this Survey is automatically linked when a Survey or a Campaign are saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
        migrations.DeleteModel(
            name='Expedition',
        ),
        migrations.DeleteModel(
            name='FieldMediaAttachment',
        ),
    ]
