# Generated by Django 3.2.20 on 2023-08-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230109_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('code',)},
        ),
    ]
