# Generated by Django 5.2.15 on 2026-07-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_organisation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_marine_wildlife',
            field=models.BooleanField(default=False, verbose_name='Marine Wildlife module access'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_tagging',
            field=models.BooleanField(default=False, verbose_name='Turtle Tagging module access'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_tracks_nests',
            field=models.BooleanField(default=False, verbose_name='Tracks and Nests module access'),
        ),
    ]
