# Generated by Django 5.2.15 on 2026-08-10 06:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_can_access_marine_wildlife_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=20)),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_pk', models.TextField(blank=True)),
                ('object_repr', models.TextField(blank=True)),
                ('path', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
