# Generated by Django 4.2.8 on 2023-12-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wamtram2", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trtentrybatches",
            options={
                "managed": False,
                "ordering": ["entry_batch_id"],
                "verbose_name": "Entry Batch",
                "verbose_name_plural": "Entry Batches",
            },
        ),
        migrations.AlterModelOptions(
            name="trtmeasurements",
            options={},
        ),
        migrations.AlterModelOptions(
            name="trtpersons",
            options={"managed": False, "ordering": ["first_name", "surname"]},
        ),
        migrations.AlterModelOptions(
            name="trtpittags",
            options={
                "managed": False,
                "ordering": ["pit_tag_id"],
                "verbose_name": "Pit tag",
            },
        ),
        migrations.AlterModelOptions(
            name="trtplaces",
            options={"managed": False, "ordering": ["place_name"]},
        ),
        migrations.AlterModelOptions(
            name="trttags",
            options={
                "managed": False,
                "ordering": ["tag_id"],
                "verbose_name": "Flipper tag",
            },
        ),
        migrations.AlterModelOptions(
            name="trtturtles",
            options={
                "managed": False,
                "ordering": ["turtle_id"],
                "verbose_name": "Turtle",
            },
        ),
    ]
