# Generated by Django 4.2.8 on 2023-12-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wamtram2", "0002_alter_trtentrybatches_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trtmeasurements",
            options={"managed": False},
        ),
    ]
