# Generated by Django 4.2.11 on 2024-04-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wamtram2", "0003_alter_trtmeasurements_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trtdataentry",
            options={"managed": False, "ordering": ["-data_entry_id"]},
        ),
        migrations.AlterModelOptions(
            name="trtpersons",
            options={
                "managed": False,
                "ordering": ["first_name", "surname"],
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
        migrations.AlterModelOptions(
            name="trtpittags",
            options={
                "managed": False,
                "ordering": ["pittag_id"],
                "verbose_name": "Pit tag",
            },
        ),
        migrations.AlterModelOptions(
            name="trttagorders",
            options={
                "managed": False,
                "verbose_name": "Tag Order",
                "verbose_name_plural": "Tag Orders",
            },
        ),
    ]
