# Generated by Django 5.2.15 on 2026-06-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wamtram2', '0004_alter_trtdataentry_options_alter_trtpersons_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrtEntryBatchOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(db_column='organisation_code', max_length=50)),
            ],
            options={
                'db_table': 'TRT_ENTRY_BATCHES_ORGANISATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(db_column='TEMPLATE_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255, unique=True)),
                ('location_code', models.CharField(blank=True, db_column='LOCATIONS_CODE', max_length=50, null=True)),
                ('place_code', models.CharField(blank=True, db_column='PLACE_CODE', max_length=50, null=True)),
                ('species_code', models.CharField(blank=True, db_column='SPECIES_CODE', max_length=50, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('I', 'Indeterminate')], db_column='SEX', max_length=1, null=True)),
            ],
            options={
                'db_table': 'TRT_TEMPLATES',
            },
        ),
        migrations.AlterModelOptions(
            name='trtobservations',
            options={'managed': False, 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AlterModelOptions(
            name='trtpittags',
            options={'managed': False, 'ordering': ['pittag_id'], 'verbose_name': 'Pit tag', 'verbose_name_plural': 'Pit tags'},
        ),
        migrations.AlterModelOptions(
            name='trttags',
            options={'managed': False, 'ordering': ['tag_id'], 'verbose_name': 'Flipper tag', 'verbose_name_plural': 'Flipper tags'},
        ),
        migrations.AlterModelOptions(
            name='trtturtles',
            options={'managed': False, 'ordering': ['turtle_id'], 'verbose_name': 'Turtle', 'verbose_name_plural': 'Turtles'},
        ),
    ]
