apiVersion: batch/v1
kind: CronJob
metadata:
  name: turtles-cronjob
spec:
  # 12:30 daily (AWST -> UTC)
  schedule: '30 4 * * *'
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
            - name: turtles-cronjob
              args: ['manage.py', 'automated_qa_checks']
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: turtles-env-prod
                      key: DATABASE_URL
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: turtles-env-prod
                      key: SENTRY_DSN
                - name: SENTRY_SAMPLE_RATE
                  valueFrom:
                    secretKeyRef:
                      name: turtles-env-prod
                      key: SENTRY_SAMPLE_RATE
                - name: SENTRY_TRANSACTION_SAMPLE_RATE
                  valueFrom:
                    secretKeyRef:
                      name: turtles-env-prod
                      key: SENTRY_TRANSACTION_SAMPLE_RATE
                - name: SENTRY_ENVIRONMENT
                  value: 'prod'
