# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:23
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The primary contact number including national prefix, e.g. +61 4 12 345 678. Spaces are accepted but will be removed on saving.', max_length=128, null=True, verbose_name='Phone Number'),
        ),
    ]
