# Generated by Django 2.1.7 on 2019-05-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190301_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.TextField(blank=True, help_text='The organisational affiliation of the user.', verbose_name='Affiliation'),
        ),
    ]
