# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161020_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, help_text='The role of the user.', max_length=1000, null=True, verbose_name='Role of User'),
        ),
    ]
