# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 08:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(blank=True, help_text='The observation datetime', null=True, verbose_name='Observed on')),
                ('where', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The observation location as point in WGS84', null=True, srid=4326, verbose_name='Observed at')),
                ('who', models.ForeignKey(blank=True, help_text='The observer as system user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Observed by')),
            ],
        ),
    ]
