# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cetaceanencounter',
            name='animalencounter_ptr',
        ),
        migrations.RemoveField(
            model_name='turtleencounter',
            name='animalencounter_ptr',
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='maturity',
            field=models.CharField(choices=[('turtle-hatchling', 'hatchling turtle'), ('turtle-post-hatchling', 'post-hatchling turtle'), ('turtle-juvenile', 'juvenile turtle'), ('turtle-pre-pubsecent-immature', 'pre-pubsecent immature turtle'), ('turtle-pubsecent-immature', 'pubsecent immature turtle'), ('turtle-adult-measured', 'adult turtle (status determined from carapace and tail measurements)'), ('turtle-adult', 'adult turtle'), ('turtle-unknown', 'unknown maturity turtle'), ('mammal-unweaned', 'unweaned immature mammal'), ('mammal-weaned', 'weaned immature mammal'), ('mammal-adult', 'adult mammal'), ('mammal-unknown', 'unknown maturity mammal')], default='unknown', help_text="The animal's maturity.", max_length=300, verbose_name='Maturity'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='algal_growth',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Algal growth on carapace'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='barnacles',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Barnacles'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='damage_injury',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Obvious damage or injuries'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='missing_limbs',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Missing limbs'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='propeller_damage',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Propeller strike damage'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='scanned_for_pit_tags',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Scanned for PIT tags'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='tagging_scars',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Tagging scars'),
        ),
        migrations.DeleteModel(
            name='CetaceanEncounter',
        ),
        migrations.DeleteModel(
            name='TurtleEncounter',
        ),
    ]
