# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20160810_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalencounter',
            name='taxon',
            field=models.CharField(choices=[('Cheloniidae', 'Marine turtles'), ('Cetacea', 'Whales and Dolphins'), ('Pinnipedia', 'Pinnipeds'), ('Sirenia', 'Dugongs'), ('Elasmobranchii', 'Sharks and Rays'), ('na', 'Unknown')], default='na', help_text='The taxonomic group of the animal.', max_length=300, verbose_name='Taxonomic group'),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='activity',
            field=models.CharField(choices=[('na', 'not observed'), ('arriving', 'arriving on beach'), ('digging-body-pit', 'digging body pit'), ('excavating-egg-chamber', 'excavating egg chamber'), ('laying-eggs', 'laying eggs'), ('filling-in-egg-chamber', 'filling in egg chamber'), ('returning-to-water', 'returning to water'), ('floating', 'Floating (dead, sick, unable to dive, drifting in water)'), ('beach-washed', 'Beach washed (dead, sick or stranded on beach/coast)'), ('beach-jumped', 'Beach jumped'), ('carcass-tagged-released', 'Carcass tagged and released'), ('carcass-inland', 'Carcass or butchered remains found removed from coast'), ('captivity', 'In captivity'), ('non-breeding', 'General non-breeding activity (swimming, sleeping, feeding, etc.)'), ('other', 'other activity')], default='na', help_text="The animal's activity at the time of observation.", max_length=300, verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='habitat',
            field=models.CharField(choices=[('na', 'not observed'), ('beach', 'B - Beach: Below the vegetation line of the grass slope'), ('bays-estuaries', 'BE - Bays, estuaries and other enclosed shallow soft sediments'), ('dune', 'D - Dune'), ('dune-constructed-hard-substrate', 'DC - Dune: Constructed hard substrate (concrete slabs, timber floors, helipad)'), ('dune-grass-area', 'DG - Dune: Grass area'), ('dune-compacted-path', 'DH - Dune: Hard compacted areas (road ways, paths)'), ('dune-rubble', 'DR - Dune: Rubble, usually coral'), ('dune-bare-sand', 'DS - Dune: Bare sand area'), ('dune-beneath-vegetation', 'DT - Dune: Beneath tree or shrub'), ('slope-front-dune', 'S - Slope: Front slope of dune'), ('sand-flats', 'SF - Sand flats'), ('slope-grass', 'SG - Slope: Grass area'), ('slope-bare-sand', 'SS - Slope: Bare sand area'), ('slope-beneath-vegetation', 'ST - Slope: Beneath tree or shrub'), ('below-mean-spring-high-water-mark', 'HW - Below the mean spring high water line or current level of inundation'), ('lagoon-patch-reef', 'LP - Lagoon: Patch reef'), ('lagoon-open-sand', 'LS - Lagoon: Open sand areas, typically shallow'), ('mangroves', 'M - Mangroves'), ('reef-coral', 'R - Reef: Coral reef'), ('reef-crest-front-slope', 'RC - Reef: Reef crest (dries at low water) and front reef slope areas'), ('reef-flat', 'RF - Reef: Reef flat, dries at low tide'), ('reef-seagrass-flats', 'RG - Coral reef with seagrass flats'), ('reef-rocky', 'RR - Reef: Rocky reef, e.g. adjacent to mainland'), ('open-water', 'OW - Open water, including inter reefal areas')], default='na', help_text='The habitat in which the animal was encountered.', max_length=500, verbose_name='Habitat'),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='health',
            field=models.CharField(choices=[('na', 'not observed'), ('alive', 'Alive (healthy)'), ('alive-injured', 'Alive (injured)'), ('alive-then-died', 'Initally alive (but died)'), ('dead-edible', 'Dead (carcass edible)'), ('dead-organs-intact', 'Dead (decomposed but organs intact)'), ('dead-advanced', 'Dead (advanced decomposition)'), ('dead-mummified', 'Mummified (dead, skin holding bones)'), ('dead-disarticulated', 'Disarticulated (dead, no soft tissue remaining)'), ('other', 'Other')], default='na', help_text='On a scale from the Fresh Prince of Bel Air to 80s Hair Metal: how dead and decomposed is the animal?', max_length=300, verbose_name='Health status'),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='maturity',
            field=models.CharField(choices=[('na', 'not observed'), ('turtle-hatchling', 'hatchling turtle'), ('turtle-post-hatchling', 'post-hatchling turtle'), ('turtle-juvenile', 'juvenile turtle'), ('turtle-pre-pubsecent-immature', 'pre-pubsecent immature turtle'), ('turtle-pubsecent-immature', 'pubsecent immature turtle'), ('turtle-adult-measured', 'adult turtle (status determined from carapace and tail measurements)'), ('turtle-adult', 'adult turtle'), ('turtle-unknown', 'unknown maturity turtle'), ('mammal-unweaned', 'unweaned immature mammal'), ('mammal-weaned', 'weaned immature mammal'), ('mammal-adult', 'adult mammal'), ('mammal-unknown', 'unknown maturity mammal')], default='na', help_text="The animal's maturity.", max_length=300, verbose_name='Maturity'),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='sex',
            field=models.CharField(choices=[('na', 'not observed'), ('male', 'male'), ('female', 'female'), ('na', 'sex not determined or not examined'), ('intersex', 'hermaphrodite or intersex')], default='na', help_text="The animal's sex.", max_length=300, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='species',
            field=models.CharField(choices=[('na', 'not observed'), ('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Leatherback turtle (Dermochelys coriacea)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('unidentified-turtle', 'Unidentified turtle'), ('Delphinus delphis', 'Delphinus delphis (Short-beaked common dolphin)'), ('Grampus griseus', "Grampus griseus (Risso's dolphin)"), ('Lagenodelphis hosei', "Lagenodelphis hosei (Fraser's dolphin)"), ('Lagenorhynchus obscurus', 'Lagenorhynchus obscurus (Dusky dolphin)'), ('Orcaella heinsohni', 'Orcaella heinsohni (Australian snubfin dolphin)'), ('Sousa sahulensis', 'Sousa sahulensis (Australian humpback dolphin)'), ('Stenella attenuata', 'Stenella attenuata (Pantropical spotted dolphin)'), ('Stenella coeruleoalba', 'Stenella coeruleoalba (Striped dolphin)'), ('Stenella longirostris', 'Stenella longirostris (Spinner dolphin)'), ('Stenella sp.', 'Stenella sp. (Unidentified spotted dolphin)'), ('Steno bredanensis', 'Steno bredanensis (Rough-toothed dolphin)'), ('Tursiops aduncus', 'Tursiops aduncus (Indo-Pacific bottlenose dolphin)'), ('Tursiops truncatus', 'Tursiops truncatus (Offshore bottlenose dolphin)'), ('Tursiops sp.', 'Tursiops sp. (Unidentified bottlenose dolphin)'), ('unidentified-dolphin', 'Unidentified dolphin'), ('Balaenoptera acutorostrata', 'Balaenoptera acutorostrata (Dwarf minke whale)'), ('Balaenoptera bonaerensis', 'Balaenoptera bonaerensis (Antarctic minke whale)<'), ('Balaenoptera borealis', 'Balaenoptera borealis (Sei whale)'), ('Balaenoptera edeni', "Balaenoptera edeni (Bryde's whale)"), ('Balaenoptera musculus', 'Balaenoptera musculus (Blue whale)'), ('Balaenoptera musculus brevicauda', 'Balaenoptera musculus brevicauda (Pygmy blue whale)'), ('Balaenoptera physalus', 'Balaenoptera physalus (Fin whale)'), ('Balaenoptera sp.', 'Balaenoptera sp. (Unidentified Balaenoptera)'), ('Eubalaena australis', 'Eubalaena australis (Southern right whale)'), ('Feresa attenuata', 'Feresa attenuata (Pygmy killer whale)'), ('Globicephala macrorhynchus', 'Globicephala macrorhynchus (Short-finned pilot whale)'), ('Globicephala melas', 'Globicephala melas (Long-finned pilot whale)'), ('Globicephala sp.', 'Globicephala sp. (Unidentified pilot whale)'), ('Indopacetus pacificus', "Indopacetus pacificus (Longman's beaked whale)"), ('Kogia breviceps', 'Kogia breviceps (Pygmy sperm whale)'), ('Kogia sima', 'Kogia sima (Dwarf sperm whale)'), ('Kogia sp.', 'Kogia sp. (Unidentified small sperm whale)'), ('Megaptera novaeangliae', 'Megaptera novaeangliae (Humpback whale)'), ('Mesoplodon densirostris', "Mesoplodon densirostris (Blainville's beaked whale)"), ('Mesoplodon layardii', 'Mesoplodon layardii (Strap-toothed whale)'), ('Mesoplodon sp.', 'Mesoplodon sp. (Beaked whale)'), ('Orcinus orca', 'Orcinus orca (Killer whale)'), ('Peponocephala electra', 'Peponocephala electra (Melon-headed whale)'), ('Physeter macrocephalus', 'Physeter macrocephalus (Sperm whale)'), ('Pseudorca crassidens', 'Pseudorca crassidens (False killer whale)'), ('Ziphius cavirostris', "Ziphius cavirostris (Cuvier's beaked whale)"), ('unidentified-whale', 'Unidentified whale')], default='unidentified', help_text='The species of the animal.', max_length=300, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='algal_growth',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Algal growth on carapace'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='barnacles',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Barnacles'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='damage_injury',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Obvious damage or injuries'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='missing_limbs',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Missing limbs'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='propeller_damage',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Propeller strike damage'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='scanned_for_pit_tags',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Scanned for PIT tags'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='tagging_scars',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Tagging scars'),
        ),
        migrations.AlterField(
            model_name='turtlenestencounter',
            name='habitat',
            field=models.CharField(choices=[('na', 'not observed'), ('beach', 'B - Beach: Below the vegetation line of the grass slope'), ('bays-estuaries', 'BE - Bays, estuaries and other enclosed shallow soft sediments'), ('dune', 'D - Dune'), ('dune-constructed-hard-substrate', 'DC - Dune: Constructed hard substrate (concrete slabs, timber floors, helipad)'), ('dune-grass-area', 'DG - Dune: Grass area'), ('dune-compacted-path', 'DH - Dune: Hard compacted areas (road ways, paths)'), ('dune-rubble', 'DR - Dune: Rubble, usually coral'), ('dune-bare-sand', 'DS - Dune: Bare sand area'), ('dune-beneath-vegetation', 'DT - Dune: Beneath tree or shrub'), ('slope-front-dune', 'S - Slope: Front slope of dune'), ('sand-flats', 'SF - Sand flats'), ('slope-grass', 'SG - Slope: Grass area'), ('slope-bare-sand', 'SS - Slope: Bare sand area'), ('slope-beneath-vegetation', 'ST - Slope: Beneath tree or shrub'), ('below-mean-spring-high-water-mark', 'HW - Below the mean spring high water line or current level of inundation'), ('lagoon-patch-reef', 'LP - Lagoon: Patch reef'), ('lagoon-open-sand', 'LS - Lagoon: Open sand areas, typically shallow'), ('mangroves', 'M - Mangroves'), ('reef-coral', 'R - Reef: Coral reef'), ('reef-crest-front-slope', 'RC - Reef: Reef crest (dries at low water) and front reef slope areas'), ('reef-flat', 'RF - Reef: Reef flat, dries at low tide'), ('reef-seagrass-flats', 'RG - Coral reef with seagrass flats'), ('reef-rocky', 'RR - Reef: Rocky reef, e.g. adjacent to mainland'), ('open-water', 'OW - Open water, including inter reefal areas')], default='na', help_text='The habitat in which the nest was encountered.', max_length=500, verbose_name='Habitat'),
        ),
        migrations.AlterField(
            model_name='turtlenestencounter',
            name='species',
            field=models.CharField(choices=[('na', 'not observed'), ('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Leatherback turtle (Dermochelys coriacea)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('unidentified-turtle', 'Unidentified turtle'), ('Delphinus delphis', 'Delphinus delphis (Short-beaked common dolphin)'), ('Grampus griseus', "Grampus griseus (Risso's dolphin)"), ('Lagenodelphis hosei', "Lagenodelphis hosei (Fraser's dolphin)"), ('Lagenorhynchus obscurus', 'Lagenorhynchus obscurus (Dusky dolphin)'), ('Orcaella heinsohni', 'Orcaella heinsohni (Australian snubfin dolphin)'), ('Sousa sahulensis', 'Sousa sahulensis (Australian humpback dolphin)'), ('Stenella attenuata', 'Stenella attenuata (Pantropical spotted dolphin)'), ('Stenella coeruleoalba', 'Stenella coeruleoalba (Striped dolphin)'), ('Stenella longirostris', 'Stenella longirostris (Spinner dolphin)'), ('Stenella sp.', 'Stenella sp. (Unidentified spotted dolphin)'), ('Steno bredanensis', 'Steno bredanensis (Rough-toothed dolphin)'), ('Tursiops aduncus', 'Tursiops aduncus (Indo-Pacific bottlenose dolphin)'), ('Tursiops truncatus', 'Tursiops truncatus (Offshore bottlenose dolphin)'), ('Tursiops sp.', 'Tursiops sp. (Unidentified bottlenose dolphin)'), ('unidentified-dolphin', 'Unidentified dolphin'), ('Balaenoptera acutorostrata', 'Balaenoptera acutorostrata (Dwarf minke whale)'), ('Balaenoptera bonaerensis', 'Balaenoptera bonaerensis (Antarctic minke whale)<'), ('Balaenoptera borealis', 'Balaenoptera borealis (Sei whale)'), ('Balaenoptera edeni', "Balaenoptera edeni (Bryde's whale)"), ('Balaenoptera musculus', 'Balaenoptera musculus (Blue whale)'), ('Balaenoptera musculus brevicauda', 'Balaenoptera musculus brevicauda (Pygmy blue whale)'), ('Balaenoptera physalus', 'Balaenoptera physalus (Fin whale)'), ('Balaenoptera sp.', 'Balaenoptera sp. (Unidentified Balaenoptera)'), ('Eubalaena australis', 'Eubalaena australis (Southern right whale)'), ('Feresa attenuata', 'Feresa attenuata (Pygmy killer whale)'), ('Globicephala macrorhynchus', 'Globicephala macrorhynchus (Short-finned pilot whale)'), ('Globicephala melas', 'Globicephala melas (Long-finned pilot whale)'), ('Globicephala sp.', 'Globicephala sp. (Unidentified pilot whale)'), ('Indopacetus pacificus', "Indopacetus pacificus (Longman's beaked whale)"), ('Kogia breviceps', 'Kogia breviceps (Pygmy sperm whale)'), ('Kogia sima', 'Kogia sima (Dwarf sperm whale)'), ('Kogia sp.', 'Kogia sp. (Unidentified small sperm whale)'), ('Megaptera novaeangliae', 'Megaptera novaeangliae (Humpback whale)'), ('Mesoplodon densirostris', "Mesoplodon densirostris (Blainville's beaked whale)"), ('Mesoplodon layardii', 'Mesoplodon layardii (Strap-toothed whale)'), ('Mesoplodon sp.', 'Mesoplodon sp. (Beaked whale)'), ('Orcinus orca', 'Orcinus orca (Killer whale)'), ('Peponocephala electra', 'Peponocephala electra (Melon-headed whale)'), ('Physeter macrocephalus', 'Physeter macrocephalus (Sperm whale)'), ('Pseudorca crassidens', 'Pseudorca crassidens (False killer whale)'), ('Ziphius cavirostris', "Ziphius cavirostris (Cuvier's beaked whale)"), ('unidentified-whale', 'Unidentified whale')], default='unidentified', help_text='The species of the animal.', max_length=300, verbose_name='Species'),
        ),
    ]
