# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20160810_1605'),
        ('observations', '0003_auto_20160810_1226'),
    ]

    operations = [
    ]
