# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20160729_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurtleStrandingObservation',
            fields=[
                ('strandingobservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.StrandingObservation')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', help_text="The animal's sex.", max_length=300, verbose_name='Sex')),
                ('maturity', models.CharField(choices=[('hatchling', 'Hatchling'), ('juvenile', 'Juvenile'), ('adult', 'Adult'), ('unknown', 'Unknown')], default='unknown', help_text="The animal's maturity.", max_length=300, verbose_name='Maturity')),
                ('curved_carapace_length_mm', models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Curved Carapace Length (mm)')),
                ('curved_carapace_length_accuracy', models.CharField(choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured')], default='unknown', help_text='The measurement type as indication of accuracy.', max_length=300, verbose_name='Curved Carapace Length Accuracy')),
                ('curved_carapace_width_mm', models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Curved Carapace Width (mm)')),
                ('curved_carapace_width_accuracy', models.CharField(choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured')], default='unknown', help_text='The measurement type as indication of accuracy.', max_length=300, verbose_name='Curved Carapace Width Accuracy')),
                ('tail_length_mm', models.PositiveIntegerField(blank=True, help_text='Tail length from carapace', null=True, verbose_name='Tail Length (mm)')),
                ('tail_length_accuracy', models.CharField(choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured')], default='unknown', help_text='The measurement type as indication of accuracy.', max_length=300, verbose_name='Tail Length Accuracy')),
                ('maximum_head_width_mm', models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Maximum Head Width (mm)')),
                ('maximum_head_width_accuracy', models.CharField(choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured')], default='unknown', help_text='The measurement type as indication of accuracy.', max_length=300, verbose_name='Maximum Head Width Accuracy')),
            ],
            options={
                'abstract': False,
            },
            bases=('observations.strandingobservation',),
        ),
        migrations.RemoveField(
            model_name='turtlemorphometrics',
            name='features',
        ),
        migrations.RemoveField(
            model_name='turtlemorphometrics',
            name='observation',
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'get_latest_by': 'when', 'ordering': ['when', 'where'], 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AddField(
            model_name='strandingobservation',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Select any observed distinguishing features.', to='observations.DistinguishingFeatures'),
        ),
        migrations.DeleteModel(
            name='TurtleMorphometrics',
        ),
    ]
