# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20160905_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTallyObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.Observation')),
                ('false_crawls_caretta_caretta', models.PositiveIntegerField(blank=True, help_text='The tally of false crawls of Caretta caretta (Loggerhead turtle).', null=True, verbose_name='False Crawls Loggerhead')),
                ('false_crawls_chelonia_mydas', models.PositiveIntegerField(blank=True, help_text='The tally of false crawls of Chelonia mydas (Green turtle).', null=True, verbose_name='False Crawls Green')),
                ('false_crawls_eretmochelys_imbricata', models.PositiveIntegerField(blank=True, help_text='The tally of false crawls of Eretmochelys imbricata (Hawksbill turtle).', null=True, verbose_name='False Crawls Hawksbill')),
                ('false_crawls_natator_depressus', models.PositiveIntegerField(blank=True, help_text='The tally of false crawls of Natator depressus (Flatback turtle).', null=True, verbose_name='False Crawls Flatback')),
                ('false_crawls_lepidochelys_olivacea', models.PositiveIntegerField(blank=True, help_text='The tally of false crawls of Lepidochelys olivacea (Olive ridley turtle).', null=True, verbose_name='False Crawls Olive ridley')),
                ('false_crawls_na', models.PositiveIntegerField(blank=True, help_text='The tally of false crawls of unknown species.', null=True, verbose_name='False Crawls of unknown species')),
            ],
            options={
                'abstract': False,
            },
            bases=('observations.observation',),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='algal_growth',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Algal growth on carapace'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='barnacles',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Barnacles'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='damage_injury',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Obvious damage or injuries'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='missing_limbs',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Missing limbs'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='propeller_damage',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Propeller strike damage'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='scanned_for_pit_tags',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Scanned for PIT tags'),
        ),
        migrations.AlterField(
            model_name='distinguishingfeatureobservation',
            name='tagging_scars',
            field=models.CharField(choices=[('na', 'Not observed'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Tagging scars'),
        ),
        migrations.AlterField(
            model_name='turtledamageobservation',
            name='damage_type',
            field=models.CharField(choices=[('minor-trauma', 'minor trauma'), ('major-trauma', 'major trauma'), ('tip-amputated', 'tip amputation'), ('amputated-from-nail', 'amputation from nail'), ('amputated-half', 'half amputation'), ('amputated-entirely', 'entire amputation'), ('tag-scar', 'tag scar'), ('tag-seen', 'tag seen but not identified'), ('cuts', 'cuts'), ('deformity', 'deformity'), ('propeller-strike', 'propeller strike'), ('entanglement', 'entanglement'), ('other', 'other')], default='minor-trauma', help_text='The type of the damage.', max_length=300, verbose_name='Damage age'),
        ),
    ]
