# Generated by Django 2.1.7 on 2019-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_auto_20190225_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('MPA', 'MPA'), ('Locality', 'Locality'), ('Site', 'Site'), ('Region', 'Region'), ('District', 'District')], default='Site', help_text='The area type.', max_length=300, verbose_name='Area type'),
        ),
    ]
