# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20160729_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistinguishingFeatures',
            new_name='DistinguishingFeature',
        ),
        migrations.AlterModelOptions(
            name='distinguishingfeature',
            options={'verbose_name': 'Distinguishing Feature', 'verbose_name_plural': 'Distinguishing Features'},
        ),
        migrations.AlterField(
            model_name='turtlestrandingobservation',
            name='curved_carapace_length_mm',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Curved Carapace Length (mm)'),
        ),
        migrations.AlterField(
            model_name='turtlestrandingobservation',
            name='curved_carapace_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Curved Carapace Width (mm)'),
        ),
        migrations.AlterField(
            model_name='turtlestrandingobservation',
            name='maximum_head_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Maximum Head Width (mm)'),
        ),
    ]
