# Generated by Django 2.1.7 on 2019-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20190408_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('MPA', 'MPA'), ('Locality', 'Locality'), ('Site', 'Site'), ('Region', 'DBCA Region'), ('District', 'DBCA District')], default='Site', help_text='The area type.', max_length=300, verbose_name='Area type'),
        ),
    ]
