# Generated by Django 2.1.7 on 2019-05-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_auto_20190502_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtlenestdisturbanceobservation',
            name='disturbance_severity',
            field=models.CharField(choices=[('negligible', 'negligible disturbance'), ('partly', 'nest partly destroyed'), ('completely', 'nest completely destroyed'), ('na', 'nest in indeterminate condition')], default='na', help_text='The impact of the disturbance on nest viability.', max_length=300, verbose_name='Disturbance severity'),
        ),
    ]
