# Generated by Django 2.1.7 on 2019-05-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_auto_20190503_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='area',
            field=models.ForeignKey(blank=True, help_text='The general area this encounter took place in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_area', to='observations.Area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The surveyed site, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_site', to='observations.Area', verbose_name='Surveyed site'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='The survey during which this encounter happened.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.Survey', verbose_name='Survey'),
        ),
    ]
