# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 08:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_auto_20160729_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaattachment',
            name='media_type',
            field=models.CharField(choices=[('data_sheet', 'Original data sheet'), ('photograph', 'Photograph'), ('other', 'Other')], default='other', help_text='What is the attached file about?', max_length=300, verbose_name='Attachment type'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 29, 8, 20, 3, 872685, tzinfo=utc), help_text='The observation datetime', verbose_name='Observed on'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='where',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT (12.1289062500000000 -1.2304687500000000)', help_text='The observation location as point in WGS84', srid=4326, verbose_name='Observed at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='who',
            field=models.ForeignKey(default='1', help_text='The observer has to be a registered system user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Observed by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strandingobservation',
            name='health',
            field=models.CharField(choices=[('alive', 'Alive, healthy'), ('alive-injured', 'Alive, injured'), ('alive-then-died', 'Initally alive, but died'), ('dead-edible', 'Dead, carcass edible'), ('dead-organs-intact', 'Dead, decomposed but organs intact'), ('dead-advanced', 'Dead, advanced decomposition'), ('dead-mummified', 'Dead, skin holding bones'), ('dead-disarticulated', 'Dead, no soft tissue remaining'), ('other', 'Other')], default='alive', help_text='On a scale from the Fresh Prince of Bel Air to 80s Hair Metal: how dead and decomposed is the animal?', max_length=300, verbose_name='Health status'),
        ),
        migrations.AlterField(
            model_name='turtlestrandingobservation',
            name='curved_carapace_length_mm',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Curved Carapace Length (mm)'),
        ),
        migrations.AlterField(
            model_name='turtlestrandingobservation',
            name='curved_carapace_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Curved Carapace Width (mm)'),
        ),
        migrations.AlterField(
            model_name='turtlestrandingobservation',
            name='maximum_head_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Maximum Head Width (mm)'),
        ),
    ]
