# Generated by Django 2.2.3 on 2019-07-09 05:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_auto_20190508_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct entry'), ('paper', 'Paper data sheet'), ('odk', 'OpenDataKit mobile data capture'), ('wamtram', 'WAMTRAM 2 tagging DB'), ('ntp-exmouth', 'NTP Access DB Exmouth'), ('ntp-broome', 'NTP Access DB Broome'), ('cet', 'Cetacean strandings DB'), ('pin', 'Pinniped strandings DB'), ('reconstructed', 'Reconstructed by WAStD')], db_index=True, default='direct', help_text='Where was this record captured initially?', max_length=300, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('proofread', 'Proofread'), ('curated', 'Curated'), ('published', 'Published')], db_index=True, default='new', max_length=50, verbose_name='QA Status'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='when',
            field=models.DateTimeField(db_index=True, help_text='The observation datetime, shown as local time (no daylight savings), stored as UTC.', verbose_name='Observed on'),
        ),
    ]
