# Generated by Django 2.2.9 on 2020-01-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_auto_20200121_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightsourceobservation',
            old_name='light_bearing_manual',
            new_name='bearing_light_degrees',
        ),
        migrations.RenameField(
            model_name='turtlehatchlingemergenceobservation',
            old_name='leftmost_track_manual',
            new_name='bearing_leftmost_track_degrees',
        ),
        migrations.RenameField(
            model_name='turtlehatchlingemergenceobservation',
            old_name='rightmost_track_manual',
            new_name='bearing_rightmost_track_degrees',
        ),
        migrations.RenameField(
            model_name='turtlehatchlingemergenceobservation',
            old_name='bearing_to_water_manual',
            new_name='bearing_to_water_degrees',
        ),
        migrations.RenameField(
            model_name='turtlehatchlingemergenceobservation',
            old_name='hatchling_emergence_time_source',
            new_name='hatchling_emergence_time_accuracy',
        ),
        migrations.RenameField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            old_name='outlier_track_bearing_manual',
            new_name='bearing_outlier_track_degrees',
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
    ]
