# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-30 03:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0018_auto_20160930_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlemorphometricobservation',
            name='body_depth_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Body depth accuracy'),
        ),
        migrations.AddField(
            model_name='turtlemorphometricobservation',
            name='body_depth_mm',
            field=models.PositiveIntegerField(blank=True, help_text='The body depth, plastron to carapace, in millimetres.', null=True, verbose_name='Body depth (mm)'),
        ),
        migrations.AddField(
            model_name='turtlemorphometricobservation',
            name='body_weight_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Body weight accuracy'),
        ),
        migrations.AddField(
            model_name='turtlemorphometricobservation',
            name='body_weight_mm',
            field=models.PositiveIntegerField(blank=True, help_text='The body weight in grams (1000 g = 1kg).', null=True, verbose_name='Body weight (g)'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='bird_predation',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Bird predation'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='croc_predation',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Crocodile predation'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='dingo_predation',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Dingo predation'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='dog_predation',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Dog predation'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='fox_predation',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Fox predation'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='goanna_predation',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Goanna predation'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='curved_carapace_length_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Curved carapace length accuracy'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='curved_carapace_width_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Curved carapace width accuracy'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='handler',
            field=models.ForeignKey(blank=True, help_text='The person conducting the measurements.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morphometric_handler', to=settings.AUTH_USER_MODEL, verbose_name='Measured by'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='maximum_head_length_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Maximum head length accuracy'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='maximum_head_width_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Maximum head width accuracy'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='recorder',
            field=models.ForeignKey(blank=True, help_text='The person recording the measurements.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morphometric_recorder', to=settings.AUTH_USER_MODEL, verbose_name='Recorded by'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='straight_carapace_length_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Straight carapace length accuracy'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='tail_length_carapace_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Tail length from carapace accuracy'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='tail_length_plastron_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Tail length from plastron accuracy'),
        ),
        migrations.AlterField(
            model_name='turtlemorphometricobservation',
            name='tail_length_vent_accuracy',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('estimated', 'Estimated'), ('measured', 'Measured'), ('1', 'To nearest mm'), ('10', 'To nearest 1 cm'), ('100', 'To nearest 10 cm'), ('1000', 'To nearest 1 m or kg'), ('10000', 'To nearest 10 m or kg')], help_text='The expected measurement accuracy.', max_length=300, null=True, verbose_name='Tail Length Accuracy'),
        ),
    ]
