# Generated by Django 3.0.8 on 2021-02-24 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wastd.observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0033_auto_20210219_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='area',
            field=models.ForeignKey(blank=True, help_text='The general area this survey took place in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_area', to='observations.Area', verbose_name='Surveyed Area'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='source_id',
            field=models.CharField(default=uuid.UUID('39f553a6-7673-11eb-ac3b-11cca3b7e6cc'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='surveymediaattachment',
            name='attachment',
            field=models.FileField(help_text='Upload the file.', max_length=500, upload_to=wastd.observations.models.survey_media, verbose_name='File attachment'),
        ),
        migrations.AlterField(
            model_name='surveymediaattachment',
            name='source_id',
            field=models.CharField(default=uuid.UUID('39f553a6-7673-11eb-ac3b-11cca3b7e6cc'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='surveymediaattachment',
            name='survey',
            field=models.ForeignKey(help_text='The Survey this attachment belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='observations.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
    ]
