# Generated by Django 3.1.13 on 2021-10-22 07:12

from django.db import migrations, models
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0036_auto_20210904_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='source_id',
            field=models.CharField(default=shared.models.make_source_id, help_text='The ID of the record in the original source, if available, or a randomly generated UUID1.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='surveymediaattachment',
            name='source_id',
            field=models.CharField(default=shared.models.make_source_id, help_text='The ID of the record in the original source, if available, or a randomly generated UUID1.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
    ]
