# Generated by Django 3.1.13 on 2021-10-22 08:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0038_auto_20211022_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetransectencounter',
            name='transect',
            field=django.contrib.gis.db.models.fields.LineStringField(help_text='The line transect as LineString in WGS84', srid=4326, verbose_name='Transect line'),
        ),
    ]
