# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0040_auto_20161019_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='bird_predation',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='croc_predation',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='dingo_predation',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='dog_predation',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='false_crawls_caretta_caretta',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='false_crawls_chelonia_mydas',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='false_crawls_eretmochelys_imbricata',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='false_crawls_lepidochelys_olivacea',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='false_crawls_na',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='false_crawls_natator_depressus',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='fox_predation',
        ),
        migrations.RemoveField(
            model_name='tracktallyobservation',
            name='goanna_predation',
        ),
        migrations.AddField(
            model_name='tracktallyobservation',
            name='species',
            field=models.CharField(choices=[('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Leatherback turtle (Dermochelys coriacea)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('unidentified-turtle', 'Unidentified turtle')], default='unidentified-turtle', help_text='The species of the animal causing the track.', max_length=300, verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='tracktallyobservation',
            name='tally',
            field=models.PositiveIntegerField(blank=True, help_text='The sum of encountered tracks.', null=True, verbose_name='Tally'),
        ),
        migrations.AddField(
            model_name='tracktallyobservation',
            name='track_type',
            field=models.CharField(choices=[('old-track', 'old track'), ('new-track', 'new track'), ('new-track-false-crawl', 'new track false crawl'), ('new-track-nesting-crawl', 'new track nesting crawl'), ('nesting-turtle-present', 'new nest turtle present'), ('fresh', 'new nest turtle absent'), ('predated', 'predated nest'), ('hatched', 'hatched nest')], default='new-track-nesting-crawl', help_text='The nest age and type.', max_length=300, verbose_name='Track type'),
        ),
        migrations.AlterField(
            model_name='turtlenestencounter',
            name='nest_age',
            field=models.CharField(choices=[('old-track', 'old track'), ('new-track', 'new track'), ('new-track-false-crawl', 'new track false crawl'), ('new-track-nesting-crawl', 'new track nesting crawl'), ('nesting-turtle-present', 'new nest turtle present'), ('fresh', 'new nest turtle absent'), ('predated', 'predated nest'), ('hatched', 'hatched nest')], default='new', help_text='The nest age and type.', max_length=300, verbose_name='Nest age'),
        ),
    ]
