# Generated by Django 3.1.13 on 2021-11-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0040_auto_20211125_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalencounter',
            name='nesting_disturbed',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='Was the nesting interrupted? If so, specify disturbance in comments.', max_length=300, verbose_name='Nesting disturbed'),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='nesting_event',
            field=models.CharField(choices=[('na', 'NA'), ('nest-with-eggs', 'Nest with eggs - witnessed egg drop'), ('nest-unsure-of-eggs', 'Nest unsure of eggs - found covered up nest mound'), ('unsure-if-nest', "Unsure if nest - can't tell whether nest mound present or not"), ('no-nest', 'No nest - witnessed aborted nest or found track with no nest')], default='na', help_text='What indication of nesting success was observed?', max_length=300, verbose_name='Nesting success'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
    ]
