# Generated by Django 3.1.13 on 2022-02-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0041_auto_20211126_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='w2_location_code',
            field=models.CharField(blank=True, help_text='The location code under which this area is known to the WAMTRAM turtle tagging database.', max_length=100, null=True, verbose_name='W2 Location Code'),
        ),
        migrations.AddField(
            model_name='area',
            name='w2_place_code',
            field=models.CharField(blank=True, help_text='The place code under which this area is known to the WAMTRAM turtle tagging database.', max_length=100, null=True, verbose_name='W2 Place Code'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
    ]
