# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0041_auto_20161020_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurtleNestDisturbanceTallyObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.Observation')),
                ('species', models.CharField(choices=[('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Leatherback turtle (Dermochelys coriacea)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('unidentified-turtle', 'Unidentified turtle')], default='unidentified-turtle', help_text='The species of the nesting animal.', max_length=300, verbose_name='Species')),
                ('disturbance_cause', models.CharField(choices=[('fox-predation', 'Fox predation'), ('dingo-predation', 'Dingo predation'), ('dog-predation', 'Dog predation'), ('goanna-predation', 'Goanna predation'), ('croc-predation', 'Croc predation'), ('bird-predation', 'Bird predation'), ('crab-predation', 'Crab predation'), ('turtle-disturbance', 'Turtle disturbance'), ('cyclone-disturbance', 'Cyclone disturbance'), ('tidal-disturbance', 'Tidal disturbance'), ('vehicle-damage', 'Vehicle damage'), ('harvest', 'Harvest'), ('research', 'Research'), ('poaching', 'Poaching'), ('other', 'Other (see comments)')], help_text='The cause of the disturbance.', max_length=300, verbose_name='Disturbance cause')),
                ('tally', models.PositiveIntegerField(blank=True, help_text='The sum of damaged nests.', null=True, verbose_name='Tally')),
            ],
            options={
                'abstract': False,
            },
            bases=('observations.observation',),
        ),
    ]
