# Generated by Django 3.1.14 on 2022-03-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0042_auto_20220210_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalencounter',
            name='sighting_status',
            field=models.CharField(choices=[('na', 'Unidentified'), ('new', 'Initial sighting'), ('resighting', 'Resighting'), ('remigrant', 'Remigrant')], default='na', help_text='Whether and where this animal was identified last.', max_length=300, verbose_name='Sighting status'),
        ),

    ]
