# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0044_auto_20161104_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlenestencounter',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments', null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='animalencounter',
            name='species',
            field=models.CharField(choices=[('na', 'not observed'), ('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Dermochelys coriacea (Leatherback turtle)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('Cheloniidae fam.', 'Chenloniidae (Unidentified turtle)'), ('Delphinus delphis', 'Delphinus delphis (Short-beaked common dolphin)'), ('Grampus griseus', "Grampus griseus (Risso's dolphin)"), ('Lagenodelphis hosei', "Lagenodelphis hosei (Fraser's dolphin)"), ('Lagenorhynchus obscurus', 'Lagenorhynchus obscurus (Dusky dolphin)'), ('Orcaella heinsohni', 'Orcaella heinsohni (Australian snubfin dolphin)'), ('Sousa sahulensis', 'Sousa sahulensis (Australian humpback dolphin)'), ('Stenella attenuata', 'Stenella attenuata (Pantropical spotted dolphin)'), ('Stenella coeruleoalba', 'Stenella coeruleoalba (Striped dolphin)'), ('Stenella longirostris', 'Stenella longirostris (Spinner dolphin)'), ('Stenella sp.', 'Stenella sp. (Unidentified spotted dolphin)'), ('Steno bredanensis', 'Steno bredanensis (Rough-toothed dolphin)'), ('Tursiops aduncus', 'Tursiops aduncus (Indo-Pacific bottlenose dolphin)'), ('Tursiops truncatus', 'Tursiops truncatus (Offshore bottlenose dolphin)'), ('Tursiops sp.', 'Tursiops sp. (Unidentified bottlenose dolphin)'), ('unidentified-dolphin', 'Unidentified dolphin'), ('Balaenoptera acutorostrata', 'Balaenoptera acutorostrata (Dwarf minke whale)'), ('Balaenoptera bonaerensis', 'Balaenoptera bonaerensis (Antarctic minke whale)<'), ('Balaenoptera borealis', 'Balaenoptera borealis (Sei whale)'), ('Balaenoptera edeni', "Balaenoptera edeni (Bryde's whale)"), ('Balaenoptera musculus', 'Balaenoptera musculus (Blue whale)'), ('Balaenoptera musculus brevicauda', 'Balaenoptera musculus brevicauda (Pygmy blue whale)'), ('Balaenoptera physalus', 'Balaenoptera physalus (Fin whale)'), ('Balaenoptera sp.', 'Balaenoptera sp. (Unidentified Balaenoptera)'), ('Eubalaena australis', 'Eubalaena australis (Southern right whale)'), ('Feresa attenuata', 'Feresa attenuata (Pygmy killer whale)'), ('Globicephala macrorhynchus', 'Globicephala macrorhynchus (Short-finned pilot whale)'), ('Globicephala melas', 'Globicephala melas (Long-finned pilot whale)'), ('Globicephala sp.', 'Globicephala sp. (Unidentified pilot whale)'), ('Indopacetus pacificus', "Indopacetus pacificus (Longman's beaked whale)"), ('Kogia breviceps', 'Kogia breviceps (Pygmy sperm whale)'), ('Kogia sima', 'Kogia sima (Dwarf sperm whale)'), ('Kogia sp.', 'Kogia sp. (Unidentified small sperm whale)'), ('Megaptera novaeangliae', 'Megaptera novaeangliae (Humpback whale)'), ('Mesoplodon densirostris', "Mesoplodon densirostris (Blainville's beaked whale)"), ('Mesoplodon layardii', 'Mesoplodon layardii (Strap-toothed whale)'), ('Mesoplodon sp.', 'Mesoplodon sp. (Beaked whale)'), ('Orcinus orca', 'Orcinus orca (Killer whale)'), ('Peponocephala electra', 'Peponocephala electra (Melon-headed whale)'), ('Physeter macrocephalus', 'Physeter macrocephalus (Sperm whale)'), ('Pseudorca crassidens', 'Pseudorca crassidens (False killer whale)'), ('Ziphius cavirostris', "Ziphius cavirostris (Cuvier's beaked whale)"), ('unidentified-whale', 'Unidentified whale'), ('hydrophiinae-subfam', 'Hydrophiinae subfam. (Sea snakes and kraits)'), ('acalyptophis-sp', 'Acalyptophis sp. (Horned sea snake)'), ('aipysurus-sp', 'Aipysurus sp. (Olive sea snake)'), ('astrotia-sp', "Astrotia sp. (Stokes' sea snake)"), ('emydocephalus-sp', 'Emydocephalus sp. (Turtlehead sea snake)'), ('enhydrina-sp', 'Enhydrina sp. (Beaked sea snake)'), ('ephalophis-sp', "Ephalophis sp. (Grey's mudsnake)"), ('hydrelaps-sp', 'Hydrelaps sp. (Port Darwin mudsnake)'), ('hydrophis-sp', 'Hydrophis sp. (sea snake)'), ('kerilia-sp', "Kerilia sp. (Jerdon's sea snake)"), ('kolpophis-sp', 'Kolpophis sp. (bighead sea snake)'), ('lapemis-sp', "Lapemis sp. (Shaw's sea snake)"), ('laticauda-sp', 'Laticauda sp. (Sea krait)'), ('parahydrophis-sp', 'Parahydrophis (Northern mangrove sea snake)'), ('parapistocalamus-sp', "Parapistocalamus sp. (Hediger's snake)"), ('pelamis-sp', 'Pelamis sp. (Yellow-bellied sea snake)'), ('praescutata-sp', 'Praescutata sp. (Sea snake)'), ('thalassophis-sp', 'Thalassophis sp. (Sea snake)')], default='unidentified', help_text='The species of the animal.', max_length=300, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='species',
            field=models.CharField(choices=[('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Dermochelys coriacea (Leatherback turtle)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('Cheloniidae fam.', 'Chenloniidae (Unidentified turtle)')], default='unidentified-turtle', help_text='The species of the animal causing the track.', max_length=300, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbanceobservation',
            name='disturbance_cause',
            field=models.CharField(choices=[('fox-predation', '(F)ox predation'), ('dingo-predation', '(Di)ngo predation'), ('dog-predation', '(D)og predation'), ('goanna-predation', '(G)oanna predation'), ('croc-predation', '(C)roc predation'), ('bandicoot-predation', '(Ba)ndicoot predation'), ('pig-predation', '(P)ig predation'), ('bird-predation', '(Bi)rd predation'), ('crab-predation', '(Cr)ab predation'), ('turtle-disturbance', ' (A)nother Turtle'), ('cyclone-disturbance', '(Cy)clone disturbance'), ('tidal-disturbance', '(T)idal disturbance'), ('vehicle-damage', '(V)ehicle damage'), ('harvest', '(Ha)rvest'), ('research', '(Re)search'), ('poaching', '(Po)aching'), ('unknown', '(U)nknown'), ('other', '(O)ther identifiable (see comments)')], help_text='The cause of the disturbance.', max_length=300, verbose_name='Disturbance cause'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbancetallyobservation',
            name='disturbance_cause',
            field=models.CharField(choices=[('fox-predation', '(F)ox predation'), ('dingo-predation', '(Di)ngo predation'), ('dog-predation', '(D)og predation'), ('goanna-predation', '(G)oanna predation'), ('croc-predation', '(C)roc predation'), ('bandicoot-predation', '(Ba)ndicoot predation'), ('pig-predation', '(P)ig predation'), ('bird-predation', '(Bi)rd predation'), ('crab-predation', '(Cr)ab predation'), ('turtle-disturbance', ' (A)nother Turtle'), ('cyclone-disturbance', '(Cy)clone disturbance'), ('tidal-disturbance', '(T)idal disturbance'), ('vehicle-damage', '(V)ehicle damage'), ('harvest', '(Ha)rvest'), ('research', '(Re)search'), ('poaching', '(Po)aching'), ('unknown', '(U)nknown'), ('other', '(O)ther identifiable (see comments)')], help_text='The cause of the disturbance.', max_length=300, verbose_name='Disturbance cause'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbancetallyobservation',
            name='species',
            field=models.CharField(choices=[('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Dermochelys coriacea (Leatherback turtle)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('Cheloniidae fam.', 'Chenloniidae (Unidentified turtle)')], default='unidentified-turtle', help_text='The species of the nesting animal.', max_length=300, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='turtlenestencounter',
            name='habitat',
            field=models.CharField(choices=[('na', 'unknown habitat'), ('beach-below-high-water', 'beach below high water mark'), ('beach-above-high-water', 'beach between high water mark and dune'), ('beach-edge-of-vegetation', 'edge of dune and vegetation'), ('in-dune-vegetation', 'inside dune and vegetation')], default='na', help_text='The habitat in which the track or nest was encountered.', max_length=500, verbose_name='Habitat'),
        ),
        migrations.AlterField(
            model_name='turtlenestencounter',
            name='species',
            field=models.CharField(choices=[('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Dermochelys coriacea (Leatherback turtle)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('Cheloniidae fam.', 'Chenloniidae (Unidentified turtle)')], default='Cheloniidae fam.', help_text='The species of the animal which created the track or nest.', max_length=300, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='turtlenestobservation',
            name='nest_position',
            field=models.CharField(choices=[('na', 'unknown habitat'), ('beach-below-high-water', 'beach below high water mark'), ('beach-above-high-water', 'beach between high water mark and dune'), ('beach-edge-of-vegetation', 'edge of dune and vegetation'), ('in-dune-vegetation', 'inside dune and vegetation')], default='unknown', help_text='The position of the nest on the beach.', max_length=300, verbose_name='Beach position'),
        ),
    ]
