# Generated by Django 3.1.14 on 2022-04-08 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0044_auto_20220401_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalencounter',
            name='site_of_first_sighting',
            field=models.ForeignKey(blank=True, help_text='The Site in which the animal was encountered first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_first_sighting', to='observations.area', verbose_name='First seen at'),
        ),
        migrations.AddField(
            model_name='animalencounter',
            name='site_of_last_sighting',
            field=models.ForeignKey(blank=True, help_text='The Site in which the animal was encountered last.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_last_sighting', to='observations.area', verbose_name='Last seen at'),
        ),
    ]
