# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0047_auto_20161110_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlenestencounter',
            name='nest_type',
            field=models.CharField(choices=[('track-false-crawl', '(F) false crawl, non-nesting'), ('track-successful-crawl', '(S) successful crawl, nesting'), ('track', '(U) turtle track, unsure whether false or successful'), ('nest', '(N) turtle nest, unhatched'), ('nest-hatched', '(H) turtle nest, hatched')], default='new-track-successful-crawl', help_text='The track or nest type.', max_length=300, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='track_type',
            field=models.CharField(choices=[('old', '(O) old'), ('fresh', '(F) fresh'), ('unknown', '(U) unknown age')], default='unknown', help_text='The nest age and type.', max_length=300, verbose_name='Track type'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbanceobservation',
            name='disturbance_severity',
            field=models.CharField(choices=[('nest-left-viable', 'nest left viable'), ('nest-destroyed', 'nest destroyed')], help_text='The impact of the disturbance on nest viability.', max_length=300, verbose_name='Disturbance severity'),
        ),
        migrations.AlterField(
            model_name='turtlenestencounter',
            name='nest_age',
            field=models.CharField(choices=[('old', '(O) old'), ('fresh', '(F) fresh'), ('unknown', '(U) unknown age')], default='unknown', help_text='The track or nest age.', max_length=300, verbose_name='Age'),
        ),
    ]
