# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0050_auto_20161110_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtlenestdisturbanceobservation',
            name='disturbance_severity',
            field=models.CharField(choices=[('nest-left-viable', 'nest left viable'), ('nest-destroyed', 'nest destroyed'), ('na', 'nest in indeterminate condition')], default='na', help_text='The impact of the disturbance on nest viability.', max_length=300, verbose_name='Disturbance severity'),
        ),
    ]
