# Generated by Django 3.2.13 on 2022-08-18 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0051_auto_20220526_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-start_time', 'destination', 'owner']},
        ),
        migrations.AddField(
            model_name='animalencounter',
            name='identifiers',
            field=models.TextField(blank=True, help_text='A space-separated list of all identifers ever recorded as associated with this animal. This list includes identifiers recorded only in earlier or later encounters.', null=True, verbose_name='Identifiers'),
        ),
        migrations.AddField(
            model_name='animalencounter',
            name='sighting_status_reason',
            field=models.CharField(blank=True, help_text='The rationale for the inferred sighting status.', max_length=1000, null=True, verbose_name='Sighting status reason'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The overarching Campaign instigating this Encounter is automatically linked when a Campaign saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='The overarching Campaign instigating this Survey is automatically linked when a Campaign is saved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.campaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='light_sources_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Light sources present during emergence'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceobservation',
            name='outlier_tracks_present',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='', max_length=300, verbose_name='Outlier tracks present'),
        ),
        migrations.AlterField(
            model_name='turtlehatchlingemergenceoutlierobservation',
            name='outlier_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='', null=True, verbose_name='Number of tracks in outlier group'),
        ),
    ]
