# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0051_auto_20161110_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtlenestdisturbanceobservation',
            name='disturbance_cause',
            field=models.CharField(choices=[('turtle', '(A)nother turtle'), ('bandicoot', '(Ba)ndicoot predation'), ('bird', '(Bi)rd predation'), ('crab', '(Cr)ab predation'), ('croc', '(Cr)oc predation'), ('cyclone', '(Cy)clone disturbance'), ('dingo', '(Di)ngo predation'), ('dog', '(Do)g predation'), ('fox', '(F)ox predation'), ('goanna', '(G)oanna predation'), ('human', '(Hu)man'), ('pig', '(P)ig predation'), ('tide', '(Ti)dal disturbance'), ('vehicle', '(V)ehicle damage'), ('unknown', '(U)nknown'), ('other', '(O)ther identifiable (see comments)')], help_text='The cause of the disturbance.', max_length=300, verbose_name='Disturbance cause'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbanceobservation',
            name='disturbance_severity',
            field=models.CharField(choices=[('partly', 'nest partly destroyed'), ('completely', 'nest completely destroyed'), ('na', 'nest in indeterminate condition')], default='na', help_text='The impact of the disturbance on nest viability.', max_length=300, verbose_name='Disturbance severity'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbancetallyobservation',
            name='disturbance_cause',
            field=models.CharField(choices=[('turtle', '(A)nother turtle'), ('bandicoot', '(Ba)ndicoot predation'), ('bird', '(Bi)rd predation'), ('crab', '(Cr)ab predation'), ('croc', '(Cr)oc predation'), ('cyclone', '(Cy)clone disturbance'), ('dingo', '(Di)ngo predation'), ('dog', '(Do)g predation'), ('fox', '(F)ox predation'), ('goanna', '(G)oanna predation'), ('human', '(Hu)man'), ('pig', '(P)ig predation'), ('tide', '(Ti)dal disturbance'), ('vehicle', '(V)ehicle damage'), ('unknown', '(U)nknown'), ('other', '(O)ther identifiable (see comments)')], help_text='The cause of the disturbance.', max_length=300, verbose_name='Disturbance cause'),
        ),
        migrations.AlterField(
            model_name='turtlenestencounter',
            name='nest_type',
            field=models.CharField(choices=[('false-crawl', '(F) false crawl, non-nesting'), ('successful-crawl', '(S) successful crawl, nesting'), ('track-unsure', '(U) turtle track, success unsure'), ('track-not-assessed', '(T) turtle track, success not assessed'), ('nest', '(N) turtle nest, unhatched'), ('hatched-nest', '(H) turtle nest, hatched')], default='new-track-successful-crawl', help_text='The track or nest type.', max_length=300, verbose_name='Type'),
        ),
    ]
