# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0052_auto_20161114_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalencounter',
            name='maturity',
            field=models.CharField(choices=[('na', 'unknown maturity'), ('hatchling', 'hatchling'), ('post-hatchling', 'post-hatchling'), ('juvenile', 'juvenile'), ('pre-pubsecent-immature', 'pre-pubsecent immature'), ('pubsecent-immature', 'pubsecent immature'), ('sub-adult', 'sub-adult'), ('adult-measured', 'adult (status determined from carapace and tail measurements)'), ('unweaned', 'unweaned immature'), ('weaned', 'weaned immature'), ('adult', 'adult')], default='na', help_text="The animal's maturity.", max_length=300, verbose_name='Maturity'),
        ),
    ]
