# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0054_auto_20161205_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct entry'), ('paper', 'Paper data sheet'), ('odk', 'OpenDataKit mobile data capture'), ('wamtram', 'WAMTRAM 2 tagging DB'), ('ntp-exmouth', 'NTP Access DB Exmouth'), ('ntp-broome', 'NTP Access DB Broome')], default='direct', help_text='Where was this record captured initially?', max_length=300, verbose_name='Data Source'),
        ),
    ]
