# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0055_auto_20161205_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turtlenestdisturbancetallyobservation',
            name='tally',
        ),
        migrations.AddField(
            model_name='turtlenestdisturbancetallyobservation',
            name='no_nests_disturbed',
            field=models.PositiveIntegerField(blank=True, help_text='The sum of damaged nests.', null=True, verbose_name='Tally of nests disturbed'),
        ),
        migrations.AddField(
            model_name='turtlenestdisturbancetallyobservation',
            name='no_tracks_encountered',
            field=models.PositiveIntegerField(blank=True, help_text='The sum of signs, e.g. predator tracks.', null=True, verbose_name='Tally of disturbance signs'),
        ),
        migrations.AlterField(
            model_name='tracktallyobservation',
            name='species',
            field=models.CharField(choices=[('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Dermochelys coriacea (Leatherback turtle)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('Cheloniidae fam.', 'Cheloniidae (Unidentified turtle)')], default='Cheloniidae fam.', help_text='The species of the animal causing the track.', max_length=300, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbancetallyobservation',
            name='disturbance_cause',
            field=models.CharField(choices=[('turtle', '(A)nother turtle'), ('bandicoot', '(Ba)ndicoot predation'), ('bird', '(Bi)rd predation'), ('crab', '(Cr)ab predation'), ('croc', '(Cr)oc predation'), ('cyclone', '(Cy)clone disturbance'), ('dingo', '(Di)ngo predation'), ('dog', '(Do)g predation'), ('fox', '(F)ox predation'), ('goanna', '(G)oanna predation'), ('human', '(Hu)man'), ('pig', '(P)ig predation'), ('tide', '(Ti)dal disturbance'), ('vehicle', '(V)ehicle damage'), ('unknown', '(U)nknown'), ('other', '(O)ther identifiable (see comments)')], default='turtle', help_text='The cause of the disturbance.', max_length=300, verbose_name='Disturbance cause'),
        ),
        migrations.AlterField(
            model_name='turtlenestdisturbancetallyobservation',
            name='species',
            field=models.CharField(choices=[('Natator depressus', 'Natator depressus (Flatback turtle)'), ('Chelonia mydas', 'Chelonia mydas (Green turtle)'), ('Eretmochelys imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('Caretta caretta', 'Caretta caretta (Loggerhead turtle)'), ('Lepidochelys olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('Dermochelys coriacea', 'Dermochelys coriacea (Leatherback turtle)'), ('Chelonia mydas agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('Corolla corolla', 'Corolla corolla (Hatchback turtle)'), ('Cheloniidae fam.', 'Cheloniidae (Unidentified turtle)')], default='Cheloniidae fam.', help_text='The species of the nesting animal.', max_length=300, verbose_name='Species'),
        ),
    ]
