# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 00:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0057_auto_20170119_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineTransectEncounter',
            fields=[
                ('encounter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.Encounter')),
                ('transect', django.contrib.gis.db.models.fields.MultiPointField(help_text='The line transect as MultiPoint in WGS84', srid=4326, verbose_name='Transect')),
            ],
            options={
                'ordering': ['when', 'where'],
                'get_latest_by': 'when',
                'verbose_name': 'Line Transect Encounter',
                'verbose_name_plural': 'Line Transect Encounters',
            },
            bases=('observations.encounter',),
        ),
    ]
