# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0060_auto_20170120_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtlenestdisturbancetallyobservation',
            name='comments',
            field=models.TextField(blank=True, help_text='Any other comments or notes.', null=True, verbose_name='Comments'),
        ),
    ]
