# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0063_auto_20170120_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtlenestobservation',
            name='no_emerged',
            field=models.PositiveIntegerField(blank=True, help_text='The number of hatchlings leaving or departed from nest.Calculated from S - (L + D).', null=True, verbose_name='Emerged (E)'),
        ),
    ]
