# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0065_auto_20170131_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagobservation',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered from manufacturer'), ('produced', 'produced by manufacturer'), ('delivered', 'delivered to HQ'), ('allocated', 'allocated to field team'), ('applied-new', 'applied new'), ('resighted', 're-sighted associated with animal'), ('reclinched', 're-sighted and reclinched on animal'), ('removed', 'taken off animal'), ('found', 'found detached'), ('returned', 'returned to HQ'), ('decommissioned', 'decommissioned'), ('destroyed', 'destroyed'), ('observed', 'observed in any other context, see comments')], default='resighted', help_text='The status this tag was seen in, or brought into.', max_length=300, verbose_name='Tag status'),
        ),
    ]
