# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0067_auto_20170201_1200'),
        ('observations', '0067_auto_20170201_1201'),
    ]

    operations = [
    ]
