# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0069_remove_turtlenestobservation_no_emerged'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestTagObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.Observation')),
                ('status', models.CharField(choices=[('applied-new', 'applied new'), ('resighted', 're-sighted associated with nest')], default='resighted', help_text='The status this tag was seen in, or brought into.', max_length=300, verbose_name='Tag status')),
                ('flipper_tag_id', models.CharField(help_text='The primary flipper tag ID of the nesting turtle if available.', max_length=1000, verbose_name='Flipper Tag ID')),
                ('date_nest_laid', models.DateField(blank=True, help_text='The calendar (not turtle) date of nest creation.', null=True, verbose_name='Date nest laid')),
                ('tag_label', models.CharField(help_text='Any extra nest label if other two components are not available.', max_length=1000, verbose_name='Tag Label')),
            ],
            options={
                'abstract': False,
            },
            bases=('observations.observation',),
        ),
    ]
