# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0071_nesttagobservation_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DugongMorphometricObservation',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.Observation')),
                ('body_length_mm', models.PositiveIntegerField(blank=True, help_text='The body length in millimetres.', null=True, verbose_name='Body length (mm)')),
                ('body_girth_mm', models.PositiveIntegerField(blank=True, help_text='The body girth at the widest point in millimetres.', null=True, verbose_name='Body girth (mm)')),
                ('tail_fluke_width_mm', models.PositiveIntegerField(blank=True, help_text='The tail fluke width in millimetres.', null=True, verbose_name='Tail fluke width (mm)')),
            ],
            options={
                'abstract': False,
            },
            bases=('observations.observation',),
        ),
    ]
