# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0072_dugongmorphometricobservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nesttagobservation',
            name='flipper_tag_id',
            field=models.CharField(blank=True, help_text='The primary flipper tag ID of the nesting turtle if available.', max_length=1000, null=True, verbose_name='Flipper Tag ID'),
        ),
        migrations.AlterField(
            model_name='nesttagobservation',
            name='tag_label',
            field=models.CharField(blank=True, help_text='Any extra nest label if other two components are not available.', max_length=1000, null=True, verbose_name='Tag Label'),
        ),
    ]
