# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0073_auto_20170203_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='dugongmorphometricobservation',
            name='tusks_found',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='Did the animal have tusks?', max_length=300, verbose_name='Tusks found'),
        ),
    ]
