# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0075_auto_20170217_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalencounter',
            name='cause_of_death',
            field=models.CharField(choices=[('na', 'not observed'), ('indeterminate-decomposed', 'Indeterminate due to decomposition'), ('boat-strike', 'Boat strike'), ('trauma-human-induced', 'Human induced trauma'), ('trauma-animal-induced', 'Animal induced trauma'), ('drowned-entangled-fisheries', 'Drowned entangled in fisheries equipment'), ('drowned-entangled-infrastructure', 'Drowned entangled in infrastructure'), ('drowned-entangled-debris', 'Drowned entangled in debris'), ('drowned-entangled', 'Drowned entangled'), ('drowned-other', 'Drowned'), ('fishery-bycatch', 'Fishery bycatch'), ('handling-accident', 'Handling accident'), ('car-collision', 'Car collision'), ('ingested-debris', 'Ingested debris'), ('harvest', 'Harvested for human consumption'), ('poisoned', 'Poisoned'), ('misorientation', 'Misorientation on beach'), ('natural', 'Natural death'), ('birthing', 'Birthing complications'), ('still-born', 'Still birth'), ('calf-failure-to-thrive', 'Calf failed to thrive'), ('starved', 'Starvation'), ('stranded', 'Stranding'), ('euthanasia-firearm', 'Euthanasia by firearm'), ('euthanasia-injection', 'Euthanasia by injection'), ('euthanasia-implosion', 'Euthanasia by implosion'), ('euthanasia', 'Euthanasia'), ('predation', 'Predation')], default='na', help_text='If dead, is the case of death known?', max_length=300, verbose_name='Cause of death'),
        ),
    ]
