# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0080_auto_20170223_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='comments',
            field=models.TextField(blank=True, help_text='Describe any circumstances affecting data collection.', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct entry'), ('paper', 'Paper data sheet'), ('odk', 'OpenDataKit mobile data capture'), ('wamtram', 'WAMTRAM 2 tagging DB'), ('ntp-exmouth', 'NTP Access DB Exmouth'), ('ntp-broome', 'NTP Access DB Broome'), ('cet', 'Cetacean strandings DB'), ('pin', 'Pinniped strandings DB')], default='direct', help_text='Where was this record captured initially?', max_length=300, verbose_name='Data Source'),
        ),
    ]
