# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 03:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0081_auto_20170224_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='transect',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='The surveyed path as LineString in WGS84.', null=True, srid=4326, verbose_name='Transect line'),
        ),
    ]
