# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0082_sitevisit_transect'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalencounter',
            name='nesting_event',
            field=models.CharField(choices=[('na', 'NA'), ('absent', 'Confirmed absent'), ('present', 'Confirmed present')], default='na', help_text='Was the animal nesting?', max_length=300, verbose_name='Nesting event'),
        ),
    ]
