# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 04:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import wastd.observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0083_animalencounter_nesting_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(help_text='The datetime of entering the site, shown as local time (no daylight savings), stored as UTC.', verbose_name='Site entered on')),
                ('finished_on', models.DateTimeField(help_text='The datetime of leaving the site, shown as local time (no daylight savings), stored as UTC.', verbose_name='Site left on')),
                ('comments', models.TextField(blank=True, help_text='Describe any circumstances affecting data collection, e.g. days without surveys.', null=True, verbose_name='Comments')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_observations.expedition_set+', to='contenttypes.ContentType')),
                ('site', models.ForeignKey(help_text='The entire surveyed area.', on_delete=django.db.models.deletion.CASCADE, to='observations.Area', verbose_name='Surveyed area')),
                ('team', models.ManyToManyField(related_name='expedition_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldMediaAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('data_sheet', 'Data sheet'), ('journal', 'Field journal'), ('communication', 'Communication record'), ('photograph', 'Photograph'), ('other', 'Other')], default='photograph', help_text='What is the attached file about?', max_length=300, verbose_name='Attachment type')),
                ('title', models.CharField(blank=True, help_text='Give the attachment a representative name', max_length=300, null=True, verbose_name='Attachment name')),
                ('attachment', models.FileField(help_text='Upload the file', max_length=500, upload_to=wastd.observations.models.expedition_media, verbose_name='File attachment')),
                ('expedition', models.ForeignKey(help_text='Surveys can be conducted during an expedition.', on_delete=django.db.models.deletion.CASCADE, to='observations.Expedition', verbose_name='Expedition')),
            ],
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='site',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='site_entered_on',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='site_left_on',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='team',
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='transect',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='The surveyed path as LineString in WGS84, optional.', null=True, srid=4326, verbose_name='Transect line'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='expedition_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.Expedition'),
            preserve_default=False,
        ),
    ]
