# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0085_auto_20170308_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct entry'), ('paper', 'Paper data sheet'), ('odk', 'OpenDataKit mobile data capture'), ('wamtram', 'WAMTRAM 2 tagging DB'), ('ntp-exmouth', 'NTP Access DB Exmouth'), ('ntp-broome', 'NTP Access DB Broome'), ('cet', 'Cetacean strandings DB'), ('pin', 'Pinniped strandings DB')], default='direct', help_text='Where was this record captured initially?', max_length=300, verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='source_id',
            field=models.CharField(blank=True, help_text='The ID of the record in the original source, or a newly allocated ID if left blank. Delete and save to regenerate this ID.', max_length=1000, null=True, verbose_name='Source ID'),
        ),
    ]
