# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0087_auto_20170308_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='expedition_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
