# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0088_auto_20170308_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalencounter',
            name='laparoscopy',
            field=models.BooleanField(default=False, help_text="Was the animal's sex and maturity determined through laparoscopy?", max_length=300, verbose_name='Laparoscopy conducted'),
        ),
        migrations.AlterField(
            model_name='turtlenestobservation',
            name='egg_count',
            field=models.PositiveIntegerField(blank=True, help_text='The total number of eggs laid as observed during tagging.', null=True, verbose_name='Total number of eggs laid'),
        ),
    ]
