# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0092_auto_20171113_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitStartEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Direct entry'), ('paper', 'Paper data sheet'), ('odk', 'OpenDataKit mobile data capture'), ('wamtram', 'WAMTRAM 2 tagging DB'), ('ntp-exmouth', 'NTP Access DB Exmouth'), ('ntp-broome', 'NTP Access DB Broome'), ('cet', 'Cetacean strandings DB'), ('pin', 'Pinniped strandings DB')], default='direct', help_text='Where was this record captured initially?', max_length=300, verbose_name='Data Source')),
                ('source_id', models.CharField(blank=True, help_text='The ID of the record in the original source, or a newly allocated ID if left blank. Delete and save to regenerate this ID.', max_length=1000, null=True, verbose_name='Source ID')),
                ('datetime', models.DateTimeField(help_text='Local time (no daylight savings), stored as UTC.', verbose_name='Observation time')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='The observation location as point in WGS84', srid=4326, verbose_name='Location')),
                ('type', models.CharField(choices=[('start', 'start'), ('end', 'end')], default='start', help_text='Start of end of site visit?', max_length=300, verbose_name='Type')),
            ],
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='end_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The end location as point in WGS84', null=True, srid=4326, verbose_name='End location'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='end_source_id',
            field=models.CharField(blank=True, help_text='The ID of the record in the original source, or a newly allocated ID if left blank. Delete and save to regenerate this ID.', max_length=1000, null=True, verbose_name='Source ID of end point'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='start_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The start location as point in WGS84', null=True, srid=4326, verbose_name='Start location'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='source_id',
            field=models.CharField(blank=True, help_text='The ID of the start point in the original source, or a newly allocated ID if left blank. Delete and save to regenerate this ID.', max_length=1000, null=True, verbose_name='Source ID'),
        ),
    ]
