# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0093_auto_20171114_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='finished_on',
            field=models.DateTimeField(blank=True, help_text='The datetime of leaving the site, shown as local time (no daylight savings), stored as UTC.', null=True, verbose_name='Site left on'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The entire surveyed area.', null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Area', verbose_name='Surveyed area'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='started_on',
            field=models.DateTimeField(blank=True, help_text='The datetime of entering the site, shown as local time (no daylight savings), stored as UTC.', null=True, verbose_name='Site entered on'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='team',
            field=models.ManyToManyField(related_name='expedition_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
