# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0095_auto_20171119_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalencounter',
            name='activity',
            field=models.CharField(choices=[('na', 'not observed'), ('arriving', 'arriving on beach'), ('approaching', 'approaching nesting site'), ('digging-body-pit', 'digging body pit'), ('excavating-egg-chamber', 'excavating egg chamber'), ('laying-eggs', 'laying eggs'), ('filling-in-egg-chamber', 'filling in egg chamber'), ('filling-in-nest', 'filling in nest'), ('camouflaging-nest', 'camouflaging nest'), ('returning-to-water', 'returning to water'), ('floating', 'floating (dead, sick, unable to dive, drifting in water)'), ('beach-washed', 'beach washed (dead, sick or stranded on beach/coast)'), ('beach-jumped', 'beach jumped'), ('carcass-tagged-released', 'carcass tagged and released'), ('carcass-inland', 'carcass or butchered remains found removed from coast'), ('captivity', 'in captivity'), ('non-breeding', 'general non-breeding activity (swimming, sleeping, feeding, etc.)'), ('other', 'other activity')], default='na', help_text="The animal's activity at the time of observation.", max_length=300, verbose_name='Activity'),
        ),
    ]
