# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 05:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import wastd.observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0098_auto_20171129_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='The exact extent of the area as polygon in WGS84.', srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The end location as point in WGS84.', null=True, srid=4326, verbose_name='Survey end point'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_photo',
            field=models.FileField(help_text='Site conditions at end of survey.', max_length=500, upload_to=wastd.observations.models.expedition_media, verbose_name='Site photo end'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text="The datetime of leaving the site, shown as local time (no daylight savings), stored as UTC. The time of 'feet in the sand, done recording encounters.'", null=True, verbose_name='Survey end time'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='The person who captured the start point, ideally this person also recoreded the encounters and end point.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recorded by'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The surveyed site, if known.', null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Area', verbose_name='Surveyed site'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='The start location as point in WGS84.', null=True, srid=4326, verbose_name='Survey start point'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_photo',
            field=models.FileField(help_text='Site conditions at start of survey.', max_length=500, upload_to=wastd.observations.models.survey_media, verbose_name='Site photo start'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text="The datetime of entering the site, shown as local time (no daylight savings), stored as UTC. The time of 'feet in the sand, start recording encounters'.", null=True, verbose_name='Survey start time'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='team',
            field=models.ManyToManyField(help_text='Additional field workers, apart from the reporter, who assisted with data collection.', related_name='survey_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='transect',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='The surveyed path as LineString in WGS84, optional. E.g. automatically captured by form Track Tally.', null=True, srid=4326, verbose_name='Transect line'),
        ),
    ]
