# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wastd.observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0101_auto_20171130_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyend',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The surveyed site, if known.', null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.Area', verbose_name='Surveyed site'),
        ),
        migrations.AlterField(
            model_name='surveyend',
            name='end_photo',
            field=models.FileField(help_text='Site conditions at end of survey.', max_length=500, upload_to=wastd.observations.models.survey_media, verbose_name='Site photo end'),
        ),
    ]
