# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0103_auto_20171202_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='area',
            field=models.ForeignKey(blank=True, help_text='The general area this encounter took place in.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_area', to='observations.Area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The surveyed site, if known.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_site', to='observations.Area', verbose_name='Surveyed site'),
        ),
    ]
