# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 06:03
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0106_auto_20180222_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('proofread', 'Proofread'), ('curated', 'Curated'), ('published', 'Published')], default='new', max_length=50, verbose_name='QA Status'),
        ),
    ]
