# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0107_survey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='team',
            field=models.ManyToManyField(blank=True, help_text='Additional field workers, apart from the reporter, who assisted with data collection.', related_name='survey_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
