# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0108_auto_20180313_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='production',
            field=models.BooleanField(default=True, help_text='Whether the survey is a real (production) survey, or a training survey.', verbose_name='Production run'),
        ),
    ]
