# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import wastd.observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0109_survey_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_photo',
            field=models.FileField(blank=True, help_text='Site conditions at end of survey.', max_length=500, null=True, upload_to=wastd.observations.models.expedition_media, verbose_name='Site photo end'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_photo',
            field=models.FileField(blank=True, help_text='Site conditions at start of survey.', max_length=500, null=True, upload_to=wastd.observations.models.survey_media, verbose_name='Site photo start'),
        ),
    ]
