# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0110_auto_20180313_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_device_id',
            field=models.CharField(blank=True, help_text='The ID of the recording device which captured the end point, if available.', max_length=1000, null=True, verbose_name='End Device ID'),
        ),
    ]
