FROM mcr.microsoft.com/mssql-tools:latest


RUN apt-get update && apt-get install -y wget unzip


RUN wget -progress=bar:force -q -O sqlpackage.zip https://aka.ms/sqlpackage-linux \
    && unzip -qq sqlpackage.zip -d /opt/sqlpackage \
    && chmod +x /opt/sqlpackage/sqlpackage \
    && rm sqlpackage.zip


ENV PATH="/opt/sqlpackage:${PATH}"

WORKDIR /backup 