# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.BigIntegerField(help_text='WACensus Name ID', unique=True, verbose_name='Name ID')),
                ('name', models.CharField(blank=True, help_text='Taxonomic Name', max_length=1000, null=True, verbose_name='Name')),
                ('full_name', models.CharField(blank=True, help_text='Taxonomic Full Name', max_length=1000, null=True, verbose_name='Full Name')),
                ('vernacular', models.CharField(blank=True, help_text='Vernacular Name', max_length=1000, null=True, verbose_name='Vernacular Name')),
                ('all_vernaculars', models.TextField(blank=True, help_text='All Vernacular Names', null=True, verbose_name='All Vernacular Names')),
                ('kingdom_id', models.BigIntegerField(blank=True, help_text='WACensus Kingdom ID', null=True, verbose_name='Kingdom ID')),
                ('family_code', models.CharField(blank=True, help_text='Taxonomic Family Code', max_length=1000, null=True, verbose_name='Family Code')),
                ('family_nid', models.BigIntegerField(blank=True, help_text='WACensus Family Name ID', null=True, verbose_name='Family ID')),
                ('rank_id', models.BigIntegerField(blank=True, help_text='WACensus Rank ID', null=True, verbose_name='Rank ID')),
                ('rank_name', models.CharField(blank=True, help_text='Taxonomic Rank Name', max_length=500, null=True, verbose_name='Rank Name')),
                ('name1', models.CharField(blank=True, help_text='Taxonomic Name 1', max_length=500, null=True, verbose_name='Name 1')),
                ('name2', models.CharField(blank=True, help_text='Taxonomic Name 2', max_length=500, null=True, verbose_name='Name 2')),
                ('rank3', models.CharField(blank=True, help_text='Taxonomic Rank 3', max_length=500, null=True, verbose_name='Rank 3')),
                ('name3', models.CharField(blank=True, help_text='Taxonomic Name 3', max_length=500, null=True, verbose_name='Name 3')),
                ('rank4', models.CharField(blank=True, help_text='Taxonomic Rank 4', max_length=500, null=True, verbose_name='Rank 4')),
                ('name4', models.CharField(blank=True, help_text='Taxonomic Name 4', max_length=500, null=True, verbose_name='Name 4')),
                ('author', models.CharField(blank=True, help_text='Taxonomic Author', max_length=1000, null=True, verbose_name='Author')),
                ('editor', models.CharField(blank=True, help_text='Taxonomic Editor', max_length=1000, null=True, verbose_name='Editor')),
                ('reference', models.CharField(blank=True, help_text='Taxonomic Reference', max_length=1000, null=True, verbose_name='Reference')),
                ('pub_id', models.BigIntegerField(blank=True, help_text='WACensus Publication ID', null=True, verbose_name='Publication ID')),
                ('vol_info', models.CharField(blank=True, help_text='Taxonomic Name 4', max_length=500, null=True, verbose_name='Name 4')),
                ('pub_year', models.IntegerField(blank=True, help_text='WACensus Publication Year', null=True, verbose_name='Publication Year')),
                ('is_current', models.NullBooleanField(help_text='WACensus currency status', verbose_name='Is name current?')),
            ],
            options={
                'ordering': ['kingdom_id', 'family_nid', 'name_id'],
                'verbose_name': 'Taxon',
                'verbose_name_plural': 'Taxa',
            },
        ),
    ]
