# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxon',
            options={'get_latest_by': 'added_on', 'ordering': ['kingdom_id', 'family_nid', 'name_id'], 'verbose_name': 'Taxon', 'verbose_name_plural': 'Taxa'},
        ),
        migrations.AddField(
            model_name='taxon',
            name='added_by',
            field=models.CharField(blank=True, help_text='The person or system who added this record to WACensus.', max_length=100, null=True, verbose_name='Added by'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='added_on',
            field=models.DateField(blank=True, help_text='Date on which this record was added to WACensus.', max_length=100, null=True, verbose_name='WACensus added on'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments are words to clarify things.', null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='form_desc_dy',
            field=models.CharField(blank=True, help_text='Day of first description', max_length=100, null=True, verbose_name='Described on (day)'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='form_desc_mn',
            field=models.CharField(blank=True, help_text='Month of first description', max_length=100, null=True, verbose_name='Described on (month)'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='form_desc_yr',
            field=models.CharField(blank=True, help_text='Year of first description', max_length=100, null=True, verbose_name='Described on (year)'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='informal',
            field=models.CharField(blank=True, help_text='The approval status indicates whether a taxonomic name is a phrase name (PN), manuscript name (MS) or published (blank).', max_length=500, null=True, verbose_name='Name approval status'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='is_eradicated',
            field=models.CharField(blank=True, help_text='is_eradicated', max_length=100, null=True, verbose_name='is_eradicated'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='linear_sequence',
            field=models.TextField(blank=True, help_text='', null=True, verbose_name='Linear sequence'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='md5_rowhash',
            field=models.CharField(blank=True, help_text='An MD5 hash of the record, used to indicate updates.', max_length=500, null=True, verbose_name='GeoServer MD5 rowhash'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='naturalised_certainty',
            field=models.CharField(blank=True, help_text='naturalised_certainty', max_length=100, null=True, verbose_name='naturalised certainty'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='naturalised_comments',
            field=models.TextField(blank=True, help_text='naturalised_comments', null=True, verbose_name='naturalised_comments'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='naturalised_status',
            field=models.CharField(blank=True, help_text='naturalised_status', max_length=100, null=True, verbose_name='naturalised status'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='origin',
            field=models.CharField(blank=True, help_text='origin', max_length=1000, null=True, verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='updated_by',
            field=models.CharField(blank=True, help_text='The person or system who updated this record last in WACensus.', max_length=100, null=True, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='updated_on',
            field=models.DateField(blank=True, help_text='Date on which this record was updated in WACensus.', max_length=100, null=True, verbose_name='WACensus updated on'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='all_vernaculars',
            field=models.TextField(blank=True, help_text='All Vernacular Names in order of preference.', null=True, verbose_name='All Vernacular Names'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full taxonomic name including author. Different concepts (defined by different authors) will have different Full Names.', max_length=1000, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='kingdom_id',
            field=models.BigIntegerField(blank=True, help_text='WACensus Kingdom ID.', null=True, verbose_name='Kingdom ID'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(blank=True, help_text='Full taxonomic name without author. Different concepts (defined by different authors) can have identical names.', max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name_id',
            field=models.BigIntegerField(help_text='WACensus Name ID, formerly known as Taxon ID. Assigned by WACensus.', unique=True, verbose_name='Name ID'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rank_id',
            field=models.BigIntegerField(blank=True, help_text='WACensus Taxonomic Rank ID.', null=True, verbose_name='Rank ID'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='rank_name',
            field=models.CharField(blank=True, help_text='WACensus Taxonomic Rank Name.', max_length=500, null=True, verbose_name='Rank Name'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='vernacular',
            field=models.CharField(blank=True, help_text='Preferred Vernacular Name.', max_length=1000, null=True, verbose_name='Preferred Vernacular Name'),
        ),
    ]
