# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20180219_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='added_on',
            field=models.CharField(blank=True, help_text='Date on which this record was added to WACensus.', max_length=100, null=True, verbose_name='WACensus added on'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='linear_sequence',
            field=models.TextField(blank=True, help_text='', null=True, verbose_name='Linear sequence'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='updated_on',
            field=models.CharField(blank=True, help_text='Date on which this record was updated in WACensus.', max_length=100, null=True, verbose_name='WACensus updated on'),
        ),
    ]
