# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_auto_20180219_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='HbvTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.BigIntegerField(help_text='WACensus Name ID, formerly known as Taxon ID. Assigned by WACensus.', unique=True, verbose_name='Name ID')),
                ('name', models.CharField(blank=True, help_text='Full taxonomic name without author. Different concepts (defined by different authors) can have identical names.', max_length=1000, null=True, verbose_name='Name')),
                ('full_name', models.CharField(blank=True, help_text='Full taxonomic name including author. Different concepts (defined by different authors) will have different Full Names.', max_length=1000, null=True, verbose_name='Full Name')),
                ('vernacular', models.CharField(blank=True, help_text='Preferred Vernacular Name.', max_length=1000, null=True, verbose_name='Preferred Vernacular Name')),
                ('all_vernaculars', models.TextField(blank=True, help_text='All Vernacular Names in order of preference.', null=True, verbose_name='All Vernacular Names')),
                ('kingdom_id', models.BigIntegerField(blank=True, help_text='WACensus Kingdom ID.', null=True, verbose_name='Kingdom ID')),
                ('family_code', models.CharField(blank=True, help_text='Taxonomic Family Code', max_length=1000, null=True, verbose_name='Family Code')),
                ('family_nid', models.BigIntegerField(blank=True, help_text='WACensus Family Name ID', null=True, verbose_name='Family ID')),
                ('rank_id', models.BigIntegerField(blank=True, help_text='WACensus Taxonomic Rank ID.', null=True, verbose_name='Rank ID')),
                ('rank_name', models.CharField(blank=True, help_text='WACensus Taxonomic Rank Name.', max_length=500, null=True, verbose_name='Rank Name')),
                ('name1', models.CharField(blank=True, help_text='Taxonomic Name 1', max_length=500, null=True, verbose_name='Name 1')),
                ('name2', models.CharField(blank=True, help_text='Taxonomic Name 2', max_length=500, null=True, verbose_name='Name 2')),
                ('rank3', models.CharField(blank=True, help_text='Taxonomic Rank 3', max_length=500, null=True, verbose_name='Rank 3')),
                ('name3', models.CharField(blank=True, help_text='Taxonomic Name 3', max_length=500, null=True, verbose_name='Name 3')),
                ('rank4', models.CharField(blank=True, help_text='Taxonomic Rank 4', max_length=500, null=True, verbose_name='Rank 4')),
                ('name4', models.CharField(blank=True, help_text='Taxonomic Name 4', max_length=500, null=True, verbose_name='Name 4')),
                ('author', models.CharField(blank=True, help_text='Taxonomic Author', max_length=1000, null=True, verbose_name='Author')),
                ('editor', models.CharField(blank=True, help_text='Taxonomic Editor', max_length=1000, null=True, verbose_name='Editor')),
                ('reference', models.CharField(blank=True, help_text='Taxonomic Reference', max_length=1000, null=True, verbose_name='Reference')),
                ('pub_id', models.BigIntegerField(blank=True, help_text='WACensus Publication ID', null=True, verbose_name='Publication ID')),
                ('vol_info', models.CharField(blank=True, help_text='Taxonomic Name 4', max_length=500, null=True, verbose_name='Name 4')),
                ('pub_year', models.IntegerField(blank=True, help_text='WACensus Publication Year', null=True, verbose_name='Publication Year')),
                ('form_desc_yr', models.CharField(blank=True, help_text='Year of first description.', max_length=100, null=True, verbose_name='Described on (year)')),
                ('form_desc_mn', models.CharField(blank=True, help_text='Month of first description.', max_length=100, null=True, verbose_name='Described on (month)')),
                ('form_desc_dy', models.CharField(blank=True, help_text='Day of first description.', max_length=100, null=True, verbose_name='Described on (day)')),
                ('is_current', models.CharField(blank=True, help_text='WACensus currency status.', max_length=100, null=True, verbose_name='Is name current?')),
                ('origin', models.CharField(blank=True, help_text='Origin.', max_length=1000, null=True, verbose_name='Origin')),
                ('naturalised_status', models.CharField(blank=True, help_text='Naturalisation status.', max_length=100, null=True, verbose_name='Naturalisation status')),
                ('naturalised_certainty', models.CharField(blank=True, help_text='Naturalisation certainty.', max_length=100, null=True, verbose_name='Naturalisation certainty')),
                ('naturalised_comments', models.TextField(blank=True, help_text='Naturalisation comments.', null=True, verbose_name='Naturalisation comments')),
                ('is_eradicated', models.CharField(blank=True, help_text='Whether taxon is eradicated or not.', max_length=100, null=True, verbose_name='Is eradicated?')),
                ('informal', models.CharField(blank=True, help_text='The approval status indicates whether a taxonomic name is a phrase name (PN), manuscript name (MS) or published (blank).', max_length=500, null=True, verbose_name='Name approval status')),
                ('comments', models.TextField(blank=True, help_text='Comments are words to clarify things.', null=True, verbose_name='Comments')),
                ('added_by', models.CharField(blank=True, help_text='The person or system who added this record to WACensus.', max_length=100, null=True, verbose_name='Added by')),
                ('added_on', models.CharField(blank=True, help_text='Date on which this record was added to WACensus.', max_length=100, null=True, verbose_name='WACensus added on')),
                ('updated_by', models.CharField(blank=True, help_text='The person or system who updated this record last in WACensus.', max_length=100, null=True, verbose_name='Updated by')),
                ('updated_on', models.CharField(blank=True, help_text='Date on which this record was updated in WACensus.', max_length=100, null=True, verbose_name='WACensus updated on')),
                ('linear_sequence', models.TextField(blank=True, help_text='', null=True, verbose_name='Linear sequence')),
                ('md5_rowhash', models.CharField(blank=True, help_text='An MD5 hash of the record, used to indicate updates.', max_length=500, null=True, verbose_name='GeoServer MD5 rowhash')),
                ('ogc_fid', models.CharField(blank=True, help_text='The OCG Feature ID of the record, used to identify the record.', max_length=500, null=True, verbose_name='GeoServer OGC FeatureID')),
            ],
            options={
                'ordering': ['kingdom_id', 'family_nid', 'name_id'],
                'verbose_name': 'HBV Taxon',
                'verbose_name_plural': 'HBV Taxa',
            },
        ),
        migrations.DeleteModel(
            name='Taxon',
        ),
    ]
