# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0009_auto_20180222_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HbvXrefs',
            new_name='HbvXref',
        ),
        migrations.AlterModelOptions(
            name='hbvvernacular',
            options={'verbose_name': 'HBV Vernacular Name', 'verbose_name_plural': 'HBV Vernacular Name'},
        ),
        migrations.AlterModelOptions(
            name='hbvxref',
            options={'ordering': ['authorised_on'], 'verbose_name': 'HBV Crossreference', 'verbose_name_plural': 'HBV Crossreferences'},
        ),
        migrations.RenameField(
            model_name='hbvgenus',
            old_name='genus_id',
            new_name='genusid',
        ),
        migrations.RemoveField(
            model_name='hbvfamily',
            name='class_name_id',
        ),
        migrations.RemoveField(
            model_name='hbvfamily',
            name='division_name_id',
        ),
        migrations.RemoveField(
            model_name='hbvfamily',
            name='order_name_id',
        ),
        migrations.AddField(
            model_name='hbvfamily',
            name='class_nid',
            field=models.BigIntegerField(blank=True, help_text='WACensus NameID, assigned by WACensus.', null=True, verbose_name='Class NameID'),
        ),
        migrations.AddField(
            model_name='hbvfamily',
            name='division_nid',
            field=models.BigIntegerField(blank=True, help_text='WACensus NameID, assigned by WACensus.', null=True, verbose_name='Division NameID'),
        ),
        migrations.AddField(
            model_name='hbvfamily',
            name='kimgdom_nid',
            field=models.BigIntegerField(blank=True, help_text='WACensus NameID, assigned by WACensus.', null=True, verbose_name='Kingdom NameID'),
        ),
        migrations.AddField(
            model_name='hbvfamily',
            name='order_nid',
            field=models.BigIntegerField(blank=True, help_text='WACensus NameID, assigned by WACensus.', null=True, verbose_name='Order NameID'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='class_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='division_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='family_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='kingdom_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Kingdom Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='order_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='supra_code',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvgroup',
            name='class_id',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvgroup',
            name='name',
            field=models.CharField(blank=True, help_text='.', max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='consv_code',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Conservation Code'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='naturalised',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Naturalised'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='ranking',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Ranking'),
        ),
    ]
