# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0014_auto_20180222_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hbvgenus',
            options={'ordering': ['kingdom_id', 'genus'], 'verbose_name': 'HBV Genus', 'verbose_name_plural': 'HBV Genera'},
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='class_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='division_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='family_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='kingdom_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Kingdom Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='order_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='supra_code',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvgroup',
            name='class_id',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='consv_code',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Conservation Code'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='naturalised',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Naturalised'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='ranking',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='hbvxref',
            name='new_name_id',
            field=models.BigIntegerField(blank=True, help_text='WACensus NameID, assigned by WACensus.', null=True, verbose_name='New NameID'),
        ),
        migrations.AlterField(
            model_name='hbvxref',
            name='ogc_fid',
            field=models.BigIntegerField(blank=True, help_text='The OCG Feature ID of the record, used to identify the record in GeoServer.', null=True, verbose_name='GeoServer OGC FeatureID'),
        ),
        migrations.AlterField(
            model_name='hbvxref',
            name='old_name_id',
            field=models.BigIntegerField(blank=True, help_text='WACensus NameID, assigned by WACensus.', null=True, verbose_name='Old NameID'),
        ),
        migrations.AlterField(
            model_name='hbvxref',
            name='xref_id',
            field=models.BigIntegerField(blank=True, help_text='The WACensus xref ID of the record, used to identify the record in WACensus.', null=True, unique=True, verbose_name='WACensus xref ID'),
        ),
    ]
