# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0015_auto_20180222_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.BigIntegerField(help_text='WACensus NameID, assigned by WACensus.', unique=True, verbose_name='NameID')),
                ('name', models.CharField(blank=True, help_text='The taxon name.', max_length=1000, null=True, verbose_name='Taxon Name')),
                ('rank', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Domain'), (10, 'Kingdom'), (20, 'Subkingdom'), (30, 'Division'), (40, 'Subivision'), (50, 'Class'), (60, 'Subclass'), (70, 'Order'), (80, 'Suborder'), (90, 'Family'), (100, 'Subfamily'), (110, 'Tribe'), (120, 'Subtribe'), (130, 'Genus'), (140, 'Subgenus'), (150, 'Section'), (160, 'Subsection'), (170, 'Series'), (180, 'Subseries'), (190, 'Species'), (200, 'Subspecies'), (210, 'Variety'), (220, 'Subvariety'), (230, 'Forma'), (240, 'Subforma')], help_text='The taxonomic rank of the taxon.', null=True, verbose_name='Taxonomic Rank')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='The lowest known parent taxon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.Taxon', verbose_name='Parent Taxon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='class_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='division_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='family_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='kingdom_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Kingdom Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='order_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='supra_code',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvgroup',
            name='class_id',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='consv_code',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Conservation Code'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='naturalised',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Naturalised'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='ranking',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Ranking'),
        ),
    ]
