# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0020_auto_20180308_0947'),
        ('taxonomy', '0020_auto_20180308_1054'),
    ]

    operations = [
    ]
