# Generated by Django 2.2.3 on 2019-07-09 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0029_auto_20190709_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='A short community codename.', max_length=1000, null=True, unique=True, verbose_name='Community code'),
        ),
        migrations.AlterField(
            model_name='community',
            name='source_id',
            field=models.CharField(default=uuid.UUID('5e364a32-a20c-11e9-9097-e4b97ae3f025'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='class_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='division_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='family_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='kingdom_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Kingdom'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='order_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='supra_code',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvgroup',
            name='class_id',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvparent',
            name='class_id',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='WACensus ClassID'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='consv_code',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Conservation Code'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='naturalised',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Naturalised'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='ranking',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='hbvsupra',
            name='supra_code',
            field=models.CharField(blank=True, db_index=True, help_text='A short code.', max_length=1000, null=True, unique=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvvernacular',
            name='name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hbvvernacular',
            name='vernacular',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Vernacular Name'),
        ),
        migrations.AlterField(
            model_name='hbvxref',
            name='authorised_on',
            field=models.CharField(blank=True, db_index=True, help_text='Date on which this record was authorised in WACensus.', max_length=100, null=True, verbose_name='WACensus authorised on'),
        ),
        migrations.AlterIndexTogether(
            name='hbvfamily',
            index_together={('kingdom_name', 'division_name', 'class_name', 'order_name', 'family_name')},
        ),
        migrations.AlterIndexTogether(
            name='hbvgenus',
            index_together={('kingdom_id', 'family_nid', 'genusid')},
        ),
        migrations.AlterIndexTogether(
            name='hbvgroup',
            index_together={('class_id', 'rank_name', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='hbvname',
            index_together={('kingdom_id', 'family_nid', 'name_id')},
        ),
        migrations.AlterIndexTogether(
            name='hbvspecies',
            index_together={('kingdom_id', 'genus', 'species')},
        ),
    ]
