# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0033_auto_20180326_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xref_id', models.BigIntegerField(blank=True, help_text='The WACensus xref ID of the record.', null=True, unique=True, verbose_name='WACensus xref ID')),
                ('reason', models.PositiveSmallIntegerField(choices=[(0, 'Misapplied name'), (1, 'Taxonomic synonym'), (2, 'Nomenclatural synonym'), (3, 'Excluded name'), (4, 'Concept change'), (5, 'Formal description'), (6, 'Orthographic variant'), (7, 'Name in error'), (8, 'Informal Synonym')], db_index=True, default=7, help_text='The reason for the taxonomic change.', verbose_name='Reason')),
                ('authorised_by', models.CharField(blank=True, help_text='The person or system who authorised this record last in WACensus.', max_length=100, null=True, verbose_name='WACensus authorised by')),
                ('authorised_on', models.DateTimeField(blank=True, help_text='Date on which this record was authorised in WACensus.', null=True, verbose_name='WACensus authorised on')),
                ('effective_to', models.DateTimeField(blank=True, help_text='Xref considered deleted after this date if set.', null=True, verbose_name='WACensus deactivated on')),
                ('comments', models.TextField(blank=True, help_text='Comments are words to clarify things.', null=True, verbose_name='Comments')),
                ('predecessor', models.ForeignKey(help_text='The old taxon.', on_delete=django.db.models.deletion.CASCADE, related_name='predecessor', to='taxonomy.Taxon', verbose_name='Predecessor Taxon')),
                ('successor', models.ForeignKey(blank=True, help_text='The new taxon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successor', to='taxonomy.Taxon', verbose_name='Successor Taxon')),
            ],
            options={
                'verbose_name': 'Crossreference',
                'verbose_name_plural': 'Crossreferences',
            },
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='class_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='division_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='family_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Family Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='kingdom_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Kingdom'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='order_name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Order Name'),
        ),
        migrations.AlterField(
            model_name='hbvfamily',
            name='supra_code',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvgroup',
            name='class_id',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='HBV Suprafamily Group Code'),
        ),
        migrations.AlterField(
            model_name='hbvparent',
            name='class_id',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='WACensus ClassID'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='consv_code',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Conservation Code'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='naturalised',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Naturalised'),
        ),
        migrations.AlterField(
            model_name='hbvspecies',
            name='ranking',
            field=models.CharField(blank=True, help_text='', max_length=100, null=True, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='hbvvernacular',
            name='name',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hbvvernacular',
            name='vernacular',
            field=models.CharField(blank=True, help_text='', max_length=1000, null=True, verbose_name='Vernacular Name'),
        ),
    ]
