# Generated by Django 3.2.18 on 2023-05-10 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtleobservation',
            name='curation_status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('imported', 'Imported'), ('manual input', 'Manual input'), ('curated', 'Curated'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='turtleobservation',
            name='data_sheet',
            field=models.FileField(blank=True, help_text='Electronic copy of the field survey data sheet', max_length=255, null=True, upload_to='tagging/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='turtleobservation',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded the survey data in the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turtleobservations_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='User who input the survey data to the database', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turtleobservations_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporter', to=settings.AUTH_USER_MODEL, verbose_name='tagger reporter'),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='status',
            field=models.CharField(blank=True, choices=[('Initial Nesting', 'Initial Nesting'), ('Initial Sighting', 'Initial Sighting'), ('Remigrant', 'Remigrant'), ('Resighting', 'Resighting')], max_length=128, null=True, verbose_name='observation status'),
        ),
    ]
