# Generated by Django 3.2.19 on 2023-05-31 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagging', '0002_auto_20230510_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turtleobservation',
            old_name='reporter',
            new_name='tagger_reporter',
        ),
        migrations.AlterField(
            model_name='turtle',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Tag Turtles'), ('C', 'Captive'), ('E', 'Error (data not to be used)'), ('N', 'Non-tagged turtle'), ('P', 'Query new tagged'), ('Q', 'Query identity'), ('R', 'Re-entered population - Original Tag identity now unknown'), ('S', 'Salvage'), ('T', 'Tagged turtle - with full Tag history: first tag to last known')], help_text='The status of this turtle record', max_length=1, null=True),
        ),
    ]
