# Generated by Django 3.2.19 on 2023-06-09 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagging', '0003_auto_20230531_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='turtleobservation',
            name='nested',
            field=models.CharField(blank=True, choices=[('yes', 'Yes, saw eggs'), ('possible', "Possible, didn't see eggs"), ('no-nest', 'No nest'), ('uncertain', 'Uncertain'), ('dnc', "Didn't check")], help_text='Did the turtle lay?', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='turtleobservation',
            name='nesting_interrupted',
            field=models.BooleanField(help_text='Was the nesting process interruped?', null=True),
        ),
        migrations.AddField(
            model_name='turtleobservation',
            name='nesting_interruption_cause',
            field=models.CharField(blank=True, choices=[('staff', 'Tagger'), ('turtle', 'Turtle'), ('public', 'Member of the public'), ('animal', 'Other animal'), ('other', 'Other')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='User who input the survey data to the database', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='measurer',
            field=models.ForeignKey(blank=True, help_text='User who took physical measurements in the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded the survey data in the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='tagger',
            field=models.ForeignKey(blank=True, help_text='User who applied tags in the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tagger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turtleobservation',
            name='tagger_reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tagger_reporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
