apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
secretGenerator:
  - name: turtles-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../base
  - cronjobs/automated-qa
  - cronjobs/download-odk
  - cronjobs/reconstruct-missing-surveys
  - ingress.yaml
  - pdb.yaml
labels:
  - pairs:
      variant: uat
    includeSelectors: true
patches:
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
