# Generated by Django 2.0.8 on 2018-09-26 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0001_squashed_0002_auto_20180420_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityarea',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='taxonarea',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='area',
            name='encountered_by',
            field=models.ForeignKey(blank=True, help_text='The person who experience the original encounter.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Encountered by'),
        ),
    ]
