# Generated by Django 2.0.8 on 2018-10-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0003_auto_20181022_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaencounter',
            options={'ordering': ['-northern_extent', 'name'], 'verbose_name': 'Area Encounter', 'verbose_name_plural': 'Area Encounters'},
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='code',
            field=models.CharField(blank=True, help_text='A URL-safe, short code. Multiple records of the same Area will be recognised by the same area type and code.', max_length=1000, null=True, verbose_name='Code'),
        ),
    ]
