# Generated by Django 2.0.8 on 2018-10-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0004_auto_20181022_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityareaencounter',
            options={'verbose_name': 'Community Encounter', 'verbose_name_plural': 'Community Encounters'},
        ),
        migrations.AlterModelOptions(
            name='taxonareaencounter',
            options={'verbose_name': 'Taxon Encounter', 'verbose_name_plural': 'Taxon Encounters'},
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='code',
            field=models.CharField(blank=True, help_text='A URL-safe, short code for the area. Multiple records of the same Area will be recognised by the same area type and code.', max_length=1000, null=True, verbose_name='Area code'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='label',
            field=models.CharField(blank=True, editable=False, help_text="A short but comprehensive label for the encounter, populated from the model's string representation.", max_length=1000, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='name',
            field=models.CharField(blank=True, help_text='A human-readable name for the observed area.', max_length=1000, null=True, verbose_name='Area name'),
        ),
        migrations.AlterField(
            model_name='communityareaencounter',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_occurrences', to='taxonomy.Community'),
        ),
        migrations.AlterField(
            model_name='taxonareaencounter',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxon_occurrences', to='taxonomy.Taxon'),
        ),
    ]
