# Generated by Django 2.1.5 on 2019-02-04 04:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0015_auto_20190122_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaencounter',
            name='code',
            field=models.SlugField(blank=True, help_text='A URL-safe, short code for the area. Multiple records of the same Area will be recognised by the same area type and code.', max_length=1000, null=True, verbose_name='Area code'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='encountered_by',
            field=models.ForeignKey(blank=True, help_text='The person who experienced the original encounter.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Encountered by'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source',
            field=models.PositiveIntegerField(choices=[(0, 'Direct entry'), (1, 'Manual entry from paper datasheet'), (2, 'Digital data capture (ODK)'), (3, 'Partial survey'), (10, 'Threatened Fauna'), (11, 'Threatened Flora'), (12, 'Threatened Communities'), (13, 'Threatened Communities Boundaries'), (14, 'Threatened Communities Buffers'), (15, 'Threatened Communities Sites'), (20, 'Turtle Tagging Database WAMTRAM2'), (21, 'Ningaloo Turtle Program'), (22, 'Broome Turtle Program'), (23, 'Pt Hedland Turtle Program'), (24, 'Gnaraloo Turtle Program'), (25, 'Eco Beach Turtle Program'), (30, 'Cetacean Strandings Database'), (31, 'Pinniped Strandings Database')], default=0, help_text='Where was this record captured initially?', verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('66275b8a-2833-11e9-a86f-ecf4bb19b5fc'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
    ]
