# Generated by Django 2.1.7 on 2019-02-13 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0019_auto_20190213_2011'),
        ('occurrence', '0018_auto_20190211_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedSpeciesObservation',
            fields=[
                ('observationgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrence.ObservationGroup')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_species', to='taxonomy.Taxon')),
            ],
            options={
                'abstract': False,
            },
            bases=('occurrence.observationgroup',),
        ),
        migrations.CreateModel(
            name='FireHistoryObservation',
            fields=[
                ('observationgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='occurrence.ObservationGroup')),
                ('last_fire_date', models.DateField(blank=True, help_text='The estimated date of the last fire, if evident.', null=True, verbose_name='Date of last fire')),
                ('fire_intensity', models.CharField(choices=[('NA', 'NA'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='NA', help_text='Estimated intensity of last fire on a scale from High to Low, or NA if no evidence of past fires.', max_length=100, verbose_name='Fire intensity')),
            ],
            options={
                'abstract': False,
            },
            bases=('occurrence.observationgroup',),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('8589394c-2f88-11e9-a86f-40f02f6195e0'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
    ]
