# Generated by Django 2.1.7 on 2019-03-06 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import occurrence.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('occurrence', '0020_auto_20190214_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachmentObservation',
            fields=[
                ('observationgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                              parent_link=True, primary_key=True, serialize=False, to='occurrence.ObservationGroup')),
                ('attachment', models.FileField(upload_to=occurrence.models.fileattachmentobservation_media)),
                ('title', models.CharField(blank=True, help_text='A self-explanatory title for the file attachment.',
                                           max_length=500, null=True, verbose_name='Title')),
                ('confidential', models.BooleanField(db_index=True, default=True,
                                                     help_text='Whether this file is confidential or can be released to the public.', verbose_name='Is confidential')),
                ('author', models.ForeignKey(blank=True, help_text='The person who authored and endorsed this file.',
                                             null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
            bases=('occurrence.observationgroup',),
        ),
        migrations.AlterField(
            model_name='observationgroup',
            name='encounter',
            field=models.ForeignKey(help_text='The Occurrence report containing the observation group.', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='observations', to='occurrence.AreaEncounter', verbose_name='Occurrence'),
        ),
    ]
