# Generated by Django 2.1.7 on 2019-04-08 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0023_auto_20190327_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservationthreat',
            name='observationgroup_ptr',
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('82cf7208-59c6-11e9-a870-ecf4bb19b5fc'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.DeleteModel(
            name='ConservationThreat',
        ),
    ]
