# Generated by Django 2.1.7 on 2019-04-26 06:34

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0026_auto_20190426_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencecondition',
            name='completely_degraded_percent',
            field=models.PositiveIntegerField(blank=True, help_text='The proportion of habitat in percent [0..100] in completely degraded condition.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Completely_degraded [%]'),
        ),
        migrations.AddField(
            model_name='occurrencecondition',
            name='degraded_percent',
            field=models.PositiveIntegerField(blank=True, help_text='The proportion of habitat in percent [0..100] in degraded condition.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Degraded [%]'),
        ),
        migrations.AddField(
            model_name='occurrencecondition',
            name='excellent_percent',
            field=models.PositiveIntegerField(blank=True, help_text='The proportion of habitat in percent [0..100] in excellent condition.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Excellent [%]'),
        ),
        migrations.AddField(
            model_name='occurrencecondition',
            name='good_percent',
            field=models.PositiveIntegerField(blank=True, help_text='The proportion of habitat in percent [0..100] in good condition.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Good [%]'),
        ),
        migrations.AddField(
            model_name='occurrencecondition',
            name='pristine_percent',
            field=models.PositiveIntegerField(blank=True, help_text='The proportion of habitat in percent [0..100] in pristine condition.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pristine [%]'),
        ),
        migrations.AddField(
            model_name='occurrencecondition',
            name='very_good_percent',
            field=models.PositiveIntegerField(blank=True, help_text='The proportion of habitat in percent [0..100] in very good condition.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Very good [%]'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('4f50c14a-67ed-11e9-a870-40f02f6195e0'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
    ]
