# Generated by Django 2.1.7 on 2019-04-27 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('occurrence', '0028_auto_20190427_0807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OccurrenceCondition',
            new_name='HabitatCondition',
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('5b2d747e-6881-11e9-a870-40f02f6195e0'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
    ]
