# Generated by Django 2.1.7 on 2019-04-29 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0029_auto_20190427_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vegetationclassification',
            name='level1',
            field=models.TextField(blank=True, help_text='The first classification level.', null=True, verbose_name='Level 1'),
        ),
        migrations.AddField(
            model_name='vegetationclassification',
            name='level2',
            field=models.TextField(blank=True, help_text='The first classification level.', null=True, verbose_name='Level 2'),
        ),
        migrations.AddField(
            model_name='vegetationclassification',
            name='level3',
            field=models.TextField(blank=True, help_text='The first classification level.', null=True, verbose_name='Level 3'),
        ),
        migrations.AddField(
            model_name='vegetationclassification',
            name='level4',
            field=models.TextField(blank=True, help_text='The first classification level.', null=True, verbose_name='Level 4'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('cd929768-6a63-11e9-a870-40f02f6195e0'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='habitatcondition',
            name='soil_condition',
            field=models.ForeignKey(blank=True, help_text='Add missing soil conditions via the data curation portal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.SoilCondition', verbose_name='Soil condition'),
        ),
    ]
