# Generated by Django 2.1.7 on 2019-05-06 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0032_auto_20190501_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CauseOfDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReproductiveMaturity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondarySigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='actions_required',
            field=models.TextField(blank=True, help_text='Any actions required, if applicable.', null=True, verbose_name='Actions required'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='actions_taken',
            field=models.TextField(blank=True, help_text='Any actions taken, if applicable.', null=True, verbose_name='Actions taken'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='distinctive_features',
            field=models.TextField(blank=True, help_text='Distinctive features of the primary observed animal. Include injuries if applicable.', null=True, verbose_name='Distinctive features'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_adult_female',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of adult females'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_adult_male',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of adult males'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_adult_unknown',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of adult unknown'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_dependent_young_female',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of dependent_young females'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_dependent_young_male',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of dependent_young males'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_dependent_young_unknown',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of dependent_young unknown'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_juvenile_female',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of juvenile females'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_juvenile_male',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of juvenile males'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='no_juvenile_unknown',
            field=models.PositiveIntegerField(blank=True, help_text='Including the primary observed animal.', null=True, verbose_name='Number of juvenile unknown'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='observation_details',
            field=models.TextField(blank=True, help_text='Any relevant details of the observation.', null=True, verbose_name='Observation details'),
        ),
        migrations.AddField(
            model_name='physicalsample',
            name='collector_id',
            field=models.TextField(blank=True, help_text='The unique collector ID.', null=True, verbose_name='Collector ID'),
        ),
        migrations.AddField(
            model_name='physicalsample',
            name='permit_id',
            field=models.TextField(blank=True, help_text='The unique permit ID.', null=True, verbose_name='Permit ID'),
        ),
        migrations.AddField(
            model_name='physicalsample',
            name='sample_label',
            field=models.TextField(blank=True, help_text='The label must be unique within the sample type.', null=True, verbose_name='Sample Label'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('6d456822-6fc2-11e9-a870-ecf4bb19b5fc'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='cause_of_death',
            field=models.ForeignKey(blank=True, help_text='The cause of death of the primary observed animal, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.CauseOfDeath', verbose_name='Cause of Death'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='detection_method',
            field=models.ForeignKey(blank=True, help_text='What brought the human observer to the Encounter?', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.DetectionMethod', verbose_name='Detection Method'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='health',
            field=models.ForeignKey(blank=True, help_text='The health status of the primary observed animal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.AnimalHealth', verbose_name='Animal Health'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='maturity',
            field=models.ForeignKey(blank=True, help_text='Reproductive Maturity of the primary observed animal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.ReproductiveMaturity', verbose_name='Reproductive Maturity'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='secondary_signs',
            field=models.ManyToManyField(blank=True, help_text='Any observed secondary signs of the animal.', to='occurrence.SecondarySigns', verbose_name='Secondary Signs'),
        ),
        migrations.AddField(
            model_name='animalobservation',
            name='species_id_confidence',
            field=models.ForeignKey(blank=True, help_text='How correct is the species ID according to the observer?', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.Confidence', verbose_name='Species ID Confidence'),
        ),
        migrations.AddField(
            model_name='physicalsample',
            name='permit_type',
            field=models.ForeignKey(blank=True, help_text='Add missing values through the data curation portal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.PermitType', verbose_name='Permit Type'),
        ),
        migrations.AddField(
            model_name='physicalsample',
            name='sample_destination',
            field=models.ForeignKey(blank=True, help_text='Add missing values through the data curation portal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.SampleDestination', verbose_name='Sample Destination'),
        ),
        migrations.AddField(
            model_name='physicalsample',
            name='sample_type',
            field=models.ForeignKey(blank=True, help_text='Add missing values through the data curation portal.', null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.SampleType', verbose_name='Sample Type'),
        ),
    ]
