# Generated by Django 2.1.7 on 2019-05-08 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0034_auto_20190507_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalobservation',
            name='cause_of_death',
            field=models.ForeignKey(blank=True, help_text='The cause of death of the primary observed animal, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.CauseOfDeath', verbose_name='Cause of Death'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='detection_method',
            field=models.ForeignKey(blank=True, help_text='What brought the human observer to the Encounter?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.DetectionMethod', verbose_name='Detection Method'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='health',
            field=models.ForeignKey(blank=True, help_text='The health status of the primary observed animal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.AnimalHealth', verbose_name='Animal Health'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='maturity',
            field=models.ForeignKey(blank=True, help_text='Reproductive Maturity of the primary observed animal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.ReproductiveMaturity', verbose_name='Reproductive Maturity'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='sex',
            field=models.ForeignKey(blank=True, help_text='The sex of the primary observed animal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.AnimalSex', verbose_name='Animal Sex'),
        ),
        migrations.AlterField(
            model_name='animalobservation',
            name='species_id_confidence',
            field=models.ForeignKey(blank=True, help_text='How correct is the species ID according to the observer?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.Confidence', verbose_name='Species ID Confidence'),
        ),
        migrations.AlterField(
            model_name='areaassessment',
            name='survey_method',
            field=models.ForeignKey(blank=True, help_text='Add missing survey methods via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.SurveyMethod', verbose_name='Survey Method'),
        ),
        migrations.AlterField(
            model_name='areaassessment',
            name='survey_type',
            field=models.ForeignKey(blank=True, help_text='Add missing survey types via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.SurveyType', verbose_name='Survey Type'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='encounter_type',
            field=models.ForeignKey(blank=True, help_text='Add missing encounter types via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.EncounterType', verbose_name='Encounter Type'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('cb5c45cc-7164-11e9-a870-ecf4bb19b5fc'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='communityareaencounter',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_occurrences', to='taxonomy.Community'),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The person who authored and endorsed this file.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_fileattachments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='habitatcomposition',
            name='drainage',
            field=models.ForeignKey(blank=True, help_text='Add missing drainage types via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.Drainage', verbose_name='Drainage'),
        ),
        migrations.AlterField(
            model_name='habitatcomposition',
            name='landform',
            field=models.ForeignKey(blank=True, help_text='The landform.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.Landform', verbose_name='Landform'),
        ),
        migrations.AlterField(
            model_name='habitatcomposition',
            name='rock_type',
            field=models.ForeignKey(blank=True, help_text='Add missing rock types via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.RockType', verbose_name='Rock type'),
        ),
        migrations.AlterField(
            model_name='habitatcomposition',
            name='soil_colour',
            field=models.ForeignKey(blank=True, help_text='Add missing soil colours via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.SoilColour', verbose_name='Soil colour'),
        ),
        migrations.AlterField(
            model_name='habitatcomposition',
            name='soil_type',
            field=models.ForeignKey(blank=True, help_text='Add missing soil types via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.SoilType', verbose_name='Soil type'),
        ),
        migrations.AlterField(
            model_name='habitatcondition',
            name='soil_condition',
            field=models.ForeignKey(blank=True, help_text='Add missing soil conditions via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.SoilCondition', verbose_name='Soil condition'),
        ),
        migrations.AlterField(
            model_name='physicalsample',
            name='permit_type',
            field=models.ForeignKey(blank=True, help_text='Add missing values through the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.PermitType', verbose_name='Permit Type'),
        ),
        migrations.AlterField(
            model_name='physicalsample',
            name='sample_destination',
            field=models.ForeignKey(blank=True, help_text='Add missing values through the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.SampleDestination', verbose_name='Sample Destination'),
        ),
        migrations.AlterField(
            model_name='physicalsample',
            name='sample_type',
            field=models.ForeignKey(blank=True, help_text='Add missing values through the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.SampleType', verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='plantcount',
            name='count_accuracy',
            field=models.ForeignKey(blank=True, help_text='Add missing lookup values via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.CountAccuracy', verbose_name='Plant Count Accuracy'),
        ),
        migrations.AlterField(
            model_name='plantcount',
            name='count_method',
            field=models.ForeignKey(blank=True, help_text='Add missing lookup values via the data curation portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.CountMethod', verbose_name='Plant Count Method'),
        ),
        migrations.AlterField(
            model_name='plantcount',
            name='count_subject',
            field=models.ForeignKey(blank=True, help_text='What was counted?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.CountSubject', verbose_name='Counted Subject'),
        ),
        migrations.AlterField(
            model_name='plantcount',
            name='plant_condition',
            field=models.ForeignKey(blank=True, help_text='What condition were most of the plants in?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='occurrence.PlantCondition', verbose_name='Plant condition'),
        ),
        migrations.AlterField(
            model_name='taxonareaencounter',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxon_occurrences', to='taxonomy.Taxon'),
        ),
    ]
