# Generated by Django 2.1.7 on 2019-05-14 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0035_auto_20190508_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('006d6a14-761c-11e9-a870-ecf4bb19b5fc'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='taxonareaencounter',
            name='taxon',
            field=models.ForeignKey(help_text='The taxonomic name of the encountered subject.', on_delete=django.db.models.deletion.PROTECT, related_name='taxon_occurrences', to='taxonomy.Taxon'),
        ),
    ]
