# Generated by Django 2.1.7 on 2019-05-14 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0038_auto_20190514_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaencounter',
            name='geolocation_capture_method',
            field=models.CharField(choices=[('drawn-online-map-widget', 'Hand-drawn on online map widget'), ('gps-point', 'GPS point with text description of location extent'), ('gps-perimeter-walk', 'GPS perimeter walk'), ('dgps', 'Differential GPS capture of entire location extent')], default='drawn-online-map-widget', help_text='How were the coordinates of the geolocation captured? ', max_length=100, verbose_name='Geolocation capture method'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('67d96cf2-7621-11e9-a870-ecf4bb19b5fc'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
    ]
