# Generated by Django 2.1.7 on 2019-06-06 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0039_auto_20190514_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaencounter',
            name='encountered_by',
            field=models.ForeignKey(blank=True, help_text='The person who experienced the original encounter. DBCA staff have to visit this site to create a new profile. Add User profiles for external people through the data curation portal.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Encountered by'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('31378dee-8839-11e9-a870-40f02f6195e0'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='firehistory',
            name='fire_intensity',
            field=models.CharField(choices=[('NA', 'NA'), ('no', 'No evidence of fire'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='NA', help_text='Estimated intensity of last fire on a scale from High to Low, or NA if no evidence of past fires.', max_length=100, verbose_name='Fire intensity'),
        ),
        migrations.AlterIndexTogether(
            name='areaencounter',
            index_together={('northern_extent', 'name')},
        ),
    ]
