# Generated by Django 2.2.3 on 2019-07-12 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0043_auto_20190709_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaencounter',
            name='area_type',
            field=models.PositiveIntegerField(choices=[(0, 'Fauna Ephemeral Site'), (1, 'Fauna Permanent Site'), (3, 'Generic Partial survey'), (2, 'Critical Habitat'), (10, 'TEC Boundary'), (11, 'TEC Buffer'), (12, 'TEC Site'), (20, 'Flora Population'), (21, 'Flora Subpopulation'), (30, 'Fauna Site'), (40, 'Marine Protected Area'), (41, 'Locality')], db_index=True, default=0, help_text='What type describes the area occupied by the encounter most accurately? The area can be an opportunistic, once-off chance encounter (point), a fixed survey site (polygon), a partial or a complete survey of an area occupied by the encountered subject (polygon).', verbose_name='Area type'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='A human-readable name for the observed area.', max_length=1000, null=True, verbose_name='Area name'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='northern_extent',
            field=models.FloatField(blank=True, db_index=True, editable=False, help_text='The northernmost latitude is derived from location polygon or point and serves to sort areas.', null=True, verbose_name='Northernmost latitude'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('f2dd7a60-a46a-11e9-84cb-9cb6d0bfcf25'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
    ]
