# Generated by Django 2.2.10 on 2020-05-21 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0044_auto_20190712_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaencounter',
            options={'verbose_name': 'Area Encounter', 'verbose_name_plural': 'Area Encounters'},
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('9a56196e-9b2d-11ea-848b-556b2960e613'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='physicalsample',
            name='sample_label',
            field=models.TextField(blank=True, help_text='The label should be unique within the sample type.', null=True, verbose_name='Sample Label'),
        ),
        migrations.AlterUniqueTogether(
            name='areaencounter',
            unique_together={('source', 'source_id')},
        ),
    ]
