# Generated by Django 2.2.10 on 2020-06-09 05:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0045_auto_20200521_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityareaencounter',
            options={'ordering': ['id'], 'verbose_name': 'Community Encounter', 'verbose_name_plural': 'Community Encounters'},
        ),
        migrations.AlterModelOptions(
            name='taxonareaencounter',
            options={'ordering': ['id'], 'verbose_name': 'Taxon Encounter', 'verbose_name_plural': 'Taxon Encounters'},
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('94a9bcce-aa0e-11ea-bb32-87c4fa8d52c2'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
    ]
