# Generated by Django 2.2.13 on 2020-07-02 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0046_auto_20200609_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.UUID('f64f4fc8-bc30-11ea-8c93-97af6dbfb137'), help_text='The ID of the record in the original source, if available.', max_length=1000, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='areaencounter',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('proofread', 'Proofread'), ('curated', 'Curated'), ('published', 'Published'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='new', max_length=50, verbose_name='QA Status'),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The person who authored and endorsed this file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence_fileattachments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='observationgroup',
            name='status',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('proofread', 'Proofread'), ('curated', 'Curated'), ('published', 'Published'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='new', max_length=50, verbose_name='QA Status'),
        ),
    ]
