# Generated by Django 3.1.13 on 2021-10-22 07:12

from django.db import migrations, models
import shared.models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0049_auto_20200723_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaencounter',
            name='source_id',
            field=models.CharField(default=uuid.uuid4, help_text='The ID of the record in the original source, if available, or a randomly generated UUID1.', max_length=1000, verbose_name='Source ID'),
        ),
    ]
