# Generated by Django 3.2.21 on 2023-09-21 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('tag_prefix', models.CharField(blank=True, max_length=16, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('direct', 'Direct entry'), ('wamtram', 'WAMTRAM database')], db_index=True, default='direct', max_length=256)),
                ('source_id', models.CharField(db_index=True, default='na', help_text='The ID of this record in the original source (if applicable)', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Turtle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('direct', 'Direct entry'), ('wamtram', 'WAMTRAM database')], db_index=True, default='direct', max_length=256)),
                ('source_id', models.CharField(db_index=True, default='na', help_text='The ID of this record in the original source (if applicable)', max_length=256)),
                ('species', models.CharField(choices=[('natator-depressus', 'Natator depressus (Flatback turtle)'), ('chelonia-mydas', 'Chelonia mydas (Green turtle)'), ('eretmochelys-imbricata', 'Eretmochelys imbricata (Hawksbill turtle)'), ('caretta-caretta', 'Caretta caretta (Loggerhead turtle)'), ('lepidochelys-olivacea', 'Lepidochelys olivacea (Olive ridley turtle)'), ('dermochelys-coriacea', 'Dermochelys coriacea (Leatherback turtle)'), ('chelonia-mydas-agassazzi', 'Chelonia mydas agassazzi (Black turtle or East Pacific Green)'), ('cheloniidae-fam', 'Cheloniidae (Unidentified turtle)')], db_index=True, default='cheloniidae-fam', max_length=256)),
                ('sex', models.CharField(choices=[('unknown', 'Unknown'), ('male', 'Male'), ('female', 'Female'), ('intersex', 'Hermaphrodite or intersex')], db_index=True, default='unknown', max_length=256)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TurtleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('tag_type', models.CharField(choices=[('flipper-tag', 'Flipper tag'), ('pit-tag', 'Pit tag')], max_length=64)),
                ('side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], help_text='The side of the turtle where the tag was applied', max_length=64, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=128, null=True)),
                ('box_number', models.CharField(blank=True, max_length=128, null=True)),
                ('source', models.CharField(choices=[('direct', 'Direct entry'), ('wamtram', 'WAMTRAM database')], db_index=True, default='direct', max_length=256)),
                ('source_id', models.CharField(db_index=True, default='na', help_text='The ID of this record in the original source (if applicable)', max_length=256)),
                ('custodian', models.ForeignKey(blank=True, help_text='The person who has custodianship of the tag prior to application', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodian', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entered_by', to=settings.AUTH_USER_MODEL)),
                ('field_handler', models.ForeignKey(blank=True, help_text='The person who handled/applied the tag in the field', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turtle_tags.tagpurchaseorder')),
                ('turtle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turtle_tags.turtle')),
            ],
        ),
    ]
