# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitygazettal',
            name='is_m1',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category M1.', verbose_name='Conservation Category M1'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='is_m2',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category M2.', verbose_name='Conservation Category M2'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='is_m3',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category M3.', verbose_name='Conservation Category M3'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='is_m4',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category M4.', verbose_name='Conservation Category M4'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='is_s5',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category S5 (Migratory Bird).', verbose_name='Conservation Category S5'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='is_m1',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category M1.', verbose_name='Conservation Category M1'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='is_m2',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category M2.', verbose_name='Conservation Category M2'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='is_m3',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category M3.', verbose_name='Conservation Category M3'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='is_m4',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category M4.', verbose_name='Conservation Category M4'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='is_s5',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this Gazettal includes Conservation Category S5 (Migratory Bird).', verbose_name='Conservation Category S5'),
        ),
    ]
