# Generated by Django 2.0.8 on 2019-01-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0002_auto_20180926_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='A unique, url-safe code.', max_length=500, unique=True, verbose_name='Code')),
                ('label', models.CharField(blank=True, help_text='A human-readable, self-explanatory label.', max_length=500, null=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='intended_management_actions',
            field=models.ManyToManyField(blank=True, help_text='Actions to be undertaken on all occurences of the subject as specified in the document.', related_name='intended_population_actions', to='conservation.Action', verbose_name='Intended Management Action'),
        ),
    ]
