# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0002_auto_20180404_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitygazettal',
            name='comments',
            field=models.TextField(blank=True, help_text='Append comments on approval process as appropriate.', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='conservationcategory',
            name='description',
            field=models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='conservationcategory',
            name='label',
            field=models.CharField(blank=True, help_text='An explanatory label.', max_length=500, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='conservationcriterion',
            name='description',
            field=models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='conservationcriterion',
            name='label',
            field=models.CharField(blank=True, help_text='An explanatory label.', max_length=500, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='comments',
            field=models.TextField(blank=True, help_text='Append comments on approval process as appropriate.', null=True, verbose_name='Comments'),
        ),
    ]
