# Generated by Django 2.0.8 on 2019-01-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0003_auto_20190118_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='ManagementActionCategory',
        ),
        migrations.AlterModelOptions(
            name='managementactioncategory',
            options={'ordering': ['code'], 'verbose_name': 'Management Action Category', 'verbose_name_plural': 'Management Action Categories'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='intended_management_actions',
        ),
    ]
