# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0003_auto_20180404_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationlist',
            name='description',
            field=models.TextField(blank=True, help_text='A comprehensive description.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='conservationlist',
            name='label',
            field=models.CharField(blank=True, help_text='An explanatory label.', max_length=500, null=True, verbose_name='Label'),
        ),
    ]
