# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-04 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0004_auto_20180404_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitygazettal',
            name='is_m1',
        ),
        migrations.RemoveField(
            model_name='communitygazettal',
            name='is_m2',
        ),
        migrations.RemoveField(
            model_name='communitygazettal',
            name='is_m3',
        ),
        migrations.RemoveField(
            model_name='communitygazettal',
            name='is_m4',
        ),
        migrations.RemoveField(
            model_name='communitygazettal',
            name='is_s5',
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='is_m1',
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='is_m2',
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='is_m3',
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='is_m4',
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='is_s5',
        ),
    ]
