# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0005_auto_20180404_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationlist',
            name='scope_communities',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this list is applicable to ecological communities.', verbose_name='Applies to Communities'),
        ),
        migrations.AddField(
            model_name='conservationlist',
            name='scope_species',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this list is applicable to individual species.', verbose_name='Applies to Species'),
        ),
        migrations.RemoveField(
            model_name='communitygazettal',
            name='category',
        ),
        migrations.AddField(
            model_name='communitygazettal',
            name='category',
            field=models.ManyToManyField(help_text='The Conservation Categories can change during the approval process. Some combinations are valid, some are not.', to='conservation.ConservationCategory', verbose_name='Conservation Categories'),
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='category',
        ),
        migrations.AddField(
            model_name='taxongazettal',
            name='category',
            field=models.ManyToManyField(help_text='The Conservation Categories can change during the approval process. Some combinations are valid, some are not.', to='conservation.ConservationCategory', verbose_name='Conservation Categories'),
        ),
    ]
