# Generated by Django 2.0.8 on 2019-01-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0006_managementaction_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='management_actions',
        ),
    ]
