# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0007_auto_20180405_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygazettal',
            name='category_cache',
            field=models.TextField(blank=True, help_text='All conservation categories as string.', null=True, verbose_name='Category cache'),
        ),
        migrations.AddField(
            model_name='communitygazettal',
            name='criteria_cache',
            field=models.TextField(blank=True, help_text='All conservation criteria as string.', null=True, verbose_name='Criteria cache'),
        ),
        migrations.AddField(
            model_name='taxongazettal',
            name='category_cache',
            field=models.TextField(blank=True, help_text='All conservation categories as string.', null=True, verbose_name='Category cache'),
        ),
        migrations.AddField(
            model_name='taxongazettal',
            name='criteria_cache',
            field=models.TextField(blank=True, help_text='All conservation criteria as string.', null=True, verbose_name='Criteria cache'),
        ),
    ]
