# Generated by Django 2.0.8 on 2019-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0007_remove_document_management_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Set once the action is completed.', null=True, verbose_name='Completion date'),
        ),
        migrations.AddField(
            model_name='managementaction',
            name='expenditure',
            field=models.FloatField(blank=True, help_text='Keep a running tally of budget expended for the implementation.', null=True, verbose_name='Expenditure'),
        ),
        migrations.AddField(
            model_name='managementaction',
            name='implementation_notes',
            field=models.TextField(blank=True, help_text='Add notes as appropriate once the implementation is in progress. Separate progress from different fiscal years in paragraphs.', null=True, verbose_name='Implementation notes'),
        ),
    ]
