# Generated by Django 2.0.8 on 2019-01-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0008_auto_20190124_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managementaction',
            options={'verbose_name': 'Conservation Action', 'verbose_name_plural': 'Conservation Actions'},
        ),
        migrations.AddField(
            model_name='managementaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'New'), (20, 'Stale'), (30, 'In progress'), (40, 'Completed')], default=10, help_text='Completion status.', verbose_name='Status'),
        ),
    ]
