# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0008_auto_20180405_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitygazettal',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='The Conservation Categories can change during the approval process. Some combinations are valid, some are not.', to='conservation.ConservationCategory', verbose_name='Conservation Categories'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='criteria',
            field=models.ManyToManyField(blank=True, help_text='The Conservation Criteria form the reason for the choice of conservation category.', to='conservation.ConservationCriterion', verbose_name='Conservation Criteria'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='The Conservation Categories can change during the approval process. Some combinations are valid, some are not.', to='conservation.ConservationCategory', verbose_name='Conservation Categories'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='criteria',
            field=models.ManyToManyField(blank=True, help_text='The Conservation Criteria form the reason for the choice of conservation category.', to='conservation.ConservationCriterion', verbose_name='Conservation Criteria'),
        ),
    ]
