# Generated by Django 2.0.8 on 2019-01-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0009_auto_20190125_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagementAction',
            new_name='ConservationAction',
        ),
        migrations.RenameModel(
            old_name='ManagementActionCategory',
            new_name='ConservationActionCategory',
        ),
        migrations.AlterModelOptions(
            name='conservationactioncategory',
            options={'ordering': ['code'], 'verbose_name': 'Conservation Action Category',
                     'verbose_name_plural': 'Conservation Action Categories'},
        ),
    ]
