# Generated by Django 2.1.7 on 2019-02-15 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0010_auto_20190125_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_notes', models.TextField(blank=True, help_text='Describe the executed work.', null=True, verbose_name='Implementation notes')),
                ('completion_date', models.DateField(blank=True, help_text='The date on which this activity was completed.', null=True, verbose_name='Completion date')),
                ('expenditure', models.DecimalField(blank=True, decimal_places=2, help_text='The estimated cost of this activity.', max_digits=16, null=True, verbose_name='Expenditure')),
            ],
        ),
        migrations.AlterField(
            model_name='conservationaction',
            name='expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The running tally of budget expended as sum of reported activities.', max_digits=20, null=True, verbose_name='Expenditure'),
        ),
        migrations.AlterField(
            model_name='conservationaction',
            name='implementation_notes',
            field=models.TextField(blank=True, help_text='Add notes as appropriate once the implementation is in progress. Separate progress from different fiscal years in paragraphs. If this conservation action requires several separate activities, consider reporting a them separately as conservation activities.', null=True, verbose_name='Implementation notes'),
        ),
        migrations.AddField(
            model_name='conservationactivity',
            name='conservation_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservation.ConservationAction'),
        ),
    ]
