# Generated by Django 2.1.7 on 2019-02-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0011_auto_20190215_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conservationaction',
            options={'ordering': ['status', 'completion_date', 'category'], 'verbose_name': 'Conservation Action', 'verbose_name_plural': 'Conservation Actions'},
        ),
        migrations.AlterModelOptions(
            name='conservationactivity',
            options={'verbose_name': 'Conservation Activity', 'verbose_name_plural': 'Conservation Activities'},
        ),
    ]
