# Generated by Django 2.1.7 on 2019-03-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0012_auto_20190225_1629'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='conservationaction',
            index_together={('document', 'occurrence_area_code')},
        ),
    ]
