# Generated by Django 2.1.7 on 2019-03-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0013_auto_20190307_1119'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='conservationaction',
            index_together={('status', 'completion_date', 'category'), ('document', 'occurrence_area_code')},
        ),
    ]
