# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0013_auto_20180411_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitygazettal',
            name='scope',
            field=models.PositiveIntegerField(choices=[(0, 'Western Australia'), (1, 'Commonwealth'), (2, 'International')], default=0, help_text='In which legislation does this Gazettal apply?', verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='source',
            field=models.PositiveIntegerField(choices=[(0, 'Manual entry'), (1, 'Threatened Fauna'), (2, 'Threatened Flora'), (3, 'Threatened Communities')], default=0, help_text='Where was this record captured initially?', verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='scope',
            field=models.PositiveIntegerField(choices=[(0, 'Western Australia'), (1, 'Commonwealth'), (2, 'International')], default=0, help_text='In which legislation does this Gazettal apply?', verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='source',
            field=models.PositiveIntegerField(choices=[(0, 'Manual entry'), (1, 'Threatened Fauna'), (2, 'Threatened Flora'), (3, 'Threatened Communities')], default=0, help_text='Where was this record captured initially?', verbose_name='Data Source'),
        ),
    ]
