# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0015_auto_20180411_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conservationcategory',
            options={'ordering': ['conservation_list', 'rank'], 'verbose_name': 'Conservation Category', 'verbose_name_plural': 'Conservation Categories'},
        ),
        migrations.AlterModelOptions(
            name='conservationcriterion',
            options={'ordering': ['conservation_list', 'rank'], 'verbose_name': 'Conservation Criterion', 'verbose_name_plural': 'Conservation Criteria'},
        ),
        migrations.AddField(
            model_name='conservationcategory',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='Display order, lowest number goes first.', null=True, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='conservationcriterion',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='Display order, lowest number goes first.', null=True, verbose_name='Rank'),
        ),
    ]
