# Generated by Django 2.1.7 on 2019-03-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0015_auto_20190327_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationthreat',
            name='area_affected_percent',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='The estimated percentage (0-100) of area affected by this threat.', max_digits=3, null=True, verbose_name='Area affected [%]'),
        ),
        migrations.AddField(
            model_name='conservationthreat',
            name='current_impact',
            field=models.CharField(choices=[('NA', 'NA'), ('nil', 'Nil'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], default='NA', help_text='Current impact of threat on specified subjects.', max_length=100, verbose_name='Current Impact'),
        ),
        migrations.AddField(
            model_name='conservationthreat',
            name='potential_impact',
            field=models.CharField(choices=[('NA', 'NA'), ('nil', 'Nil'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('extreme', 'Extreme')], default='NA', help_text='Potential impact of threat on specified subjects.', max_length=100, verbose_name='Potential Impact'),
        ),
        migrations.AddField(
            model_name='conservationthreat',
            name='potential_onset',
            field=models.CharField(choices=[('NA', 'NA'), ('short-term', '(S)hort term: Within 12 months'), ('medium-term', '(M)edium term: Within 1 to 5 years'), ('long-term', '(L)ong term: after 5 years')], default='NA', help_text='Potential onset of threat on specified subjects.', max_length=100, verbose_name='Potential Onset'),
        ),
    ]
