# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0016_auto_20180411_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitygazettal',
            name='deactivated_on',
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='deactivated_on',
        ),
        migrations.AddField(
            model_name='communitygazettal',
            name='delisted_on',
            field=models.DateTimeField(blank=True, help_text='The date and time this Gazettal was de-listed, most likely superseded by another Gazettal.', null=True, verbose_name='De-listed on'),
        ),
        migrations.AddField(
            model_name='taxongazettal',
            name='delisted_on',
            field=models.DateTimeField(blank=True, help_text='The date and time this Gazettal was de-listed, most likely superseded by another Gazettal.', null=True, verbose_name='De-listed on'),
        ),
    ]
