# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0017_auto_20180411_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationlist',
            name='approval_level',
            field=models.PositiveIntegerField(choices=[(10, 'Immediate'), (20, 'Panel'), (30, 'Minister')], default=30, help_text='What is the highest required approval instance for this list?', verbose_name='Approval Level'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='scope',
            field=models.PositiveIntegerField(choices=[(0, 'WA'), (1, 'CMW'), (2, 'INT'), (3, 'AP')], default=0, help_text='In which legislation does this Gazettal apply?', verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='scope',
            field=models.PositiveIntegerField(choices=[(0, 'WA'), (1, 'CMW'), (2, 'INT'), (3, 'AP')], default=0, help_text='In which legislation does this Gazettal apply?', verbose_name='Scope'),
        ),
    ]
