# Generated by Django 2.1.7 on 2019-04-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0017_auto_20190328_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='communities',
            field=models.ManyToManyField(blank=True, help_text='A list of all communities to which this document applies to.', to='taxonomy.Community', verbose_name='Communities'),
        ),
        migrations.AlterField(
            model_name='document',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='The date and time from which this document is effective from.', null=True, verbose_name='Effective from'),
        ),
        migrations.AlterField(
            model_name='document',
            name='effective_from_commonwealth',
            field=models.DateTimeField(blank=True, help_text='The date and time from which this document was adopted by the Commonwealth.', null=True, verbose_name='Adopted by Commonwealth on'),
        ),
        migrations.AlterField(
            model_name='document',
            name='effective_to',
            field=models.DateTimeField(blank=True, help_text='The date and time to which this document is effective to.', null=True, verbose_name='Effective to'),
        ),
        migrations.AlterField(
            model_name='document',
            name='effective_to_commonwealth',
            field=models.DateTimeField(blank=True, help_text='The date and time on which this document was retired by the Commonwealth.', null=True, verbose_name='Retired by Commonwealth on'),
        ),
        migrations.AlterField(
            model_name='document',
            name='taxa',
            field=models.ManyToManyField(blank=True, help_text='A list of all taxa to which this document applies to.', to='taxonomy.Taxon', verbose_name='Taxa'),
        ),
    ]
