# Generated by Django 2.1.7 on 2019-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0018_auto_20190408_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationcategory',
            name='level',
            field=models.CharField(choices=[('threatened', 'Threatened'), ('priority', 'Priority'), ('other', 'Other')], default='other', help_text='The general conservation status, threatened, prority, or other.', max_length=500, verbose_name='Conservation level'),
        ),
        migrations.AlterField(
            model_name='conservationcategory',
            name='current',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this category should be shown for new conservation listings.', verbose_name='Is current'),
        ),
    ]
