# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0064_auto_20180413_2031'),
        ('conservation', '0019_auto_20180411_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.PositiveIntegerField(choices=[(0, 'Recovery Plan'), (5, 'Interim Recovery Plan'), (10, 'Management Plan'), (20, 'Animal Ethics Application'), (30, 'Fauna Translocation Proposal'), (40, 'Standard Operating Procedure')], default=0, help_text='The document type governs the approval process.', verbose_name='Document Type')),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'Proposed'), (40, 'In review with Branch Manager'), (45, 'In review with Regional Manager'), (50, 'In review with Division Director'), (20, 'In review with public'), (60, 'In review with Director General'), (70, 'In review with Minister'), (80, 'Active'), (90, 'Closed'), (100, 'Rejected')], db_index=True, default=0, help_text='The approval status of the Gazettal.', verbose_name='Approval status')),
                ('effective_from', models.DateTimeField(blank=True, help_text='The date from which this document is effective from.', null=True, verbose_name='Effective from')),
                ('effective_to', models.DateTimeField(blank=True, help_text='The date to which this document is effective to.', null=True, verbose_name='Effective to')),
                ('effective_from_commonwealth', models.DateTimeField(blank=True, help_text='The date from which this document was adopted by the Commonwealth.', null=True, verbose_name='Adopted by Commonwealth on')),
                ('effective_to_commonwealth', models.DateTimeField(blank=True, help_text='The date on which this document was retired by the Commonwealth.', null=True, verbose_name='Retired by Commonwealth on')),
                ('review_due', models.DateTimeField(blank=True, help_text='The date and time this Document should be reviewed.', null=True, verbose_name='Review due date')),
                ('title', models.CharField(blank=True, help_text='A concise document title.', max_length=500, null=True, verbose_name='Title')),
                ('comments', models.TextField(blank=True, help_text='Optional comments on document approval and provenance.', null=True, verbose_name='Comments')),
                ('communities', models.ManyToManyField(help_text='All communities this document applies to.', to='taxonomy.Community', verbose_name='Communities')),
                ('taxa', models.ManyToManyField(help_text='All taxa this document applies to.', to='taxonomy.Taxon', verbose_name='Taxa')),
                ('team', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Staff involved in the writing, approval, or publication of this document.')),
            ],
            options={
                'ordering': ['document_type', 'title'],
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AlterModelOptions(
            name='communitygazettal',
            options={'verbose_name': 'Community Conservation Listing', 'verbose_name_plural': 'Community Conservation Listings'},
        ),
        migrations.AlterModelOptions(
            name='taxongazettal',
            options={'verbose_name': 'Taxon Conservation Listing', 'verbose_name_plural': 'Taxon Conservation Listings'},
        ),
        migrations.RemoveField(
            model_name='communitygazettal',
            name='delisted_on',
        ),
        migrations.RemoveField(
            model_name='communitygazettal',
            name='gazetted_on',
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='delisted_on',
        ),
        migrations.RemoveField(
            model_name='taxongazettal',
            name='gazetted_on',
        ),
        migrations.AddField(
            model_name='communitygazettal',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='The date printed on the Departmental Gazettal notice containing this Conservation Listing.', null=True, verbose_name='Effective from'),
        ),
        migrations.AddField(
            model_name='communitygazettal',
            name='effective_to',
            field=models.DateTimeField(blank=True, help_text='The date and time this Conservation Listing was de-listed or otherwise ceased to be in effect.', null=True, verbose_name='Effective to'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='confidential',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this file is confidential or can be released to the public.', verbose_name='Is confidential'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='current',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this file is current or an archived version.', verbose_name='Is current'),
        ),
        migrations.AddField(
            model_name='taxongazettal',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='The date printed on the Departmental Gazettal notice containing this Conservation Listing.', null=True, verbose_name='Effective from'),
        ),
        migrations.AddField(
            model_name='taxongazettal',
            name='effective_to',
            field=models.DateTimeField(blank=True, help_text='The date and time this Conservation Listing was de-listed or otherwise ceased to be in effect.', null=True, verbose_name='Effective to'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='label_cache',
            field=models.TextField(blank=True, help_text='An auto-generated label for the Conservation Listing.', null=True, verbose_name='Gazettal label'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='proposed_on',
            field=models.DateTimeField(blank=True, help_text='The date and time this Conservation Listing was proposed on.', null=True, verbose_name='Proposed on'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='review_due',
            field=models.DateTimeField(blank=True, help_text='The date and time this Conservation Listing should be reviewed.', null=True, verbose_name='Review due date'),
        ),
        migrations.AlterField(
            model_name='communitygazettal',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Proposed'), (10, 'In review with experts'), (20, 'In review with public'), (30, 'In review with panel'), (40, 'In review with Branch Manager'), (50, 'In review with Division Director'), (60, 'In review with Director General'), (70, 'In review with Minister'), (80, 'Published'), (90, 'De-listed'), (100, 'Rejected')], db_index=True, default=0, help_text='The approval status of the Conservation Listing.', verbose_name='Approval status'),
        ),
        migrations.AlterField(
            model_name='conservationlist',
            name='approval_level',
            field=models.PositiveIntegerField(choices=[(10, 'Immediate'), (20, 'Panel'), (25, 'Director'), (30, 'Minister')], default=30, help_text='What is the highest required approval instance for this list?', verbose_name='Approval Level'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='label_cache',
            field=models.TextField(blank=True, help_text='An auto-generated label for the Conservation Listing.', null=True, verbose_name='Gazettal label'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='proposed_on',
            field=models.DateTimeField(blank=True, help_text='The date and time this Conservation Listing was proposed on.', null=True, verbose_name='Proposed on'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='review_due',
            field=models.DateTimeField(blank=True, help_text='The date and time this Conservation Listing should be reviewed.', null=True, verbose_name='Review due date'),
        ),
        migrations.AlterField(
            model_name='taxongazettal',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Proposed'), (10, 'In review with experts'), (20, 'In review with public'), (30, 'In review with panel'), (40, 'In review with Branch Manager'), (50, 'In review with Division Director'), (60, 'In review with Director General'), (70, 'In review with Minister'), (80, 'Published'), (90, 'De-listed'), (100, 'Rejected')], db_index=True, default=0, help_text='The approval status of the Conservation Listing.', verbose_name='Approval status'),
        ),
    ]
