# Generated by Django 2.1.7 on 2019-04-24 06:22

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0020_auto_20190418_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationcategory',
            name='short_code',
            field=models.CharField(choices=[('O', 'Other'), ('X', 'Presumed extinct'), ('T', 'Threatened'), ('1', 'Priority 1'), ('2', 'Priority 2'), ('3', 'Priority 2'), ('4', 'Priority 3'), ('5', 'Priority 5')], default='O', help_text='The general conservation status, threatened, prority, or other.', max_length=500, verbose_name='Conservation short code'),
        ),
        migrations.AlterField(
            model_name='communityconservationlisting',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_listings', to='taxonomy.Community'),
        ),
        migrations.AlterField(
            model_name='communityconservationlisting',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='The date printed on the Departmental ConservationListing notice containing this Conservation Listing.', null=True, verbose_name='Effective from'),
        ),
        migrations.AlterField(
            model_name='communityconservationlisting',
            name='label_cache',
            field=models.TextField(blank=True, help_text='An auto-generated label for the Conservation Listing.', null=True, verbose_name='ConservationListing label'),
        ),
        migrations.AlterField(
            model_name='communityconservationlisting',
            name='scope',
            field=models.PositiveIntegerField(choices=[(0, 'WA'), (1, 'CWTH'), (2, 'IUCN'), (3, 'AP')], default=0, help_text='In which legislation does this ConservationListing apply?', verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='conservationaction',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Choose the overarching category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='conservation.ConservationActionCategory', verbose_name='Conservation action category'),
        ),
        migrations.AlterField(
            model_name='conservationaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(10, 'New'), (20, 'Stale'), (30, 'In progress'), (40, 'Completed')], default=10, help_text='Completion status.', verbose_name='Completion status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Proposed'), (40, 'In review with Branch Manager'), (45, 'In review with Regional Manager'), (50, 'In review with Division Director'), (20, 'In review with public'), (60, 'In review with Director General'), (70, 'In review with Minister'), (80, 'Active'), (90, 'Closed'), (100, 'Rejected')], db_index=True, default=0, help_text='The approval status of the ConservationListing.', verbose_name='Approval status'),
        ),
        migrations.AlterField(
            model_name='taxonconservationlisting',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='The date printed on the Departmental ConservationListing notice containing this Conservation Listing.', null=True, verbose_name='Effective from'),
        ),
        migrations.AlterField(
            model_name='taxonconservationlisting',
            name='label_cache',
            field=models.TextField(blank=True, help_text='An auto-generated label for the Conservation Listing.', null=True, verbose_name='ConservationListing label'),
        ),
        migrations.AlterField(
            model_name='taxonconservationlisting',
            name='scope',
            field=models.PositiveIntegerField(choices=[(0, 'WA'), (1, 'CWTH'), (2, 'IUCN'), (3, 'AP')], default=0, help_text='In which legislation does this ConservationListing apply?', verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='taxonconservationlisting',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_listings', to='taxonomy.Taxon'),
        ),
    ]
