# Generated by Django 2.1.7 on 2019-05-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0021_auto_20190424_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
