# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0021_auto_20180413_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='A concise document title.', max_length=1000, verbose_name='Title'),
        ),
    ]
