# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0024_auto_20180420_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationcategory',
            name='current',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this category should be shown for new conservatin listings.', verbose_name='Is current'),
        ),
    ]
