# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservation', '0025_conservationcategory_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_reviewed_on',
            field=models.DateTimeField(blank=True, help_text='The date and time this Conservation Listing was last reviewed.', null=True, verbose_name='Last reviewed on'),
        ),
    ]
