# Generated by Django 3.2.21 on 2023-11-06 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import marine_mammal_incidents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=100)),
                ('incident_date', models.DateTimeField()),
                ('location_name', models.CharField(max_length=100)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('number_of_animals', models.IntegerField()),
                ('mass_incident', models.BooleanField()),
                ('incident_type', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=7)),
                ('age_class', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Sub-adult', 'Sub-adult'), ('Calf', 'Calf'), ('Neonate', 'Neonate'), ('Unknown', 'Unknown')], max_length=10)),
                ('length', models.DecimalField(decimal_places=2, help_text='in meters', max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, help_text='in kilograms', max_digits=6)),
                ('comments', models.TextField(blank=True)),
                ('photos_taken', models.BooleanField()),
                ('samples_taken', models.BooleanField()),
                ('post_mortem', models.BooleanField()),
                ('carcass_location_fate', models.CharField(blank=True, help_text='Carcass transported to or disposed of site', max_length=100)),
                ('entanglement_gear', models.CharField(blank=True, max_length=50)),
                ('DBCA_staff_attended', models.BooleanField()),
                ('condition_when_found', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], max_length=5)),
                ('outcome', models.CharField(max_length=100)),
                ('cause_of_death', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'species',
            },
        ),
        migrations.CreateModel(
            name='Uploaded_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=marine_mammal_incidents.models.incident_directory_path)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marine_mammal_incidents.incident')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marine_mammal_incidents.species'),
        ),
    ]
