# Generated by Django 3.2.21 on 2023-11-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine_mammal_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_file',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Attachment name'),
            preserve_default=False,
        ),
    ]
