# Generated by Django 3.2.21 on 2023-11-13 08:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marine_mammal_incidents', '0002_uploaded_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
