# Generated by Django 3.2.21 on 2023-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine_mammal_incidents', '0003_alter_incident_geo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='condition_when_found',
            field=models.CharField(choices=[('Stage 1 = alive', 'Stage 1 = alive'), ('Stage 2 = fresh', 'Stage 2 = fresh'), ('Stage 3 = mild decomposition', 'Stage 3 = mild decomposition'), ('Stage 4 = advanced decomposition', 'Stage 4 = advanced decomposition'), ('Stage 5 = mummified/skeletal', 'Stage 5 = mummified/skeletal')], max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='entanglement_gear',
            field=models.CharField(blank=True, choices=[('Fishing net', 'Fishing net'), ('Rock lobster pot/rope', 'Rock lobster pot/rope'), ('Crab pot/rope', 'Crab pot/rope'), ('Unknown origin set gear (pot/rope)', 'Unknown origin set gear (pot/rope)'), ('Rope', 'Rope'), ('Monofilament fishing line', 'Monofilament fishing line'), ('Professional longline', 'Professional longline'), ('Braided line', 'Braided line'), ('Aquaculture infrastructure', 'Aquaculture infrastructure'), ('Tackle', 'Tackle'), ('Plastic debris', 'Plastic debris'), ('Other (see comments)', 'Other (add in comments)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Stranding', 'Stranding'), ('Entanglement', 'Entanglement'), ('Entrapment', 'Entrapment'), ('Vessel collision', 'Vessel collision'), ('Unusual mortality event', 'Unusual mortality event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='outcome',
            field=models.CharField(choices=[('Euthanased', 'Euthanased'), ('Restranded and euthanased', 'Restranded and euthanased'), ('Refloated, fate unknown', 'Refloated, fate unknown'), ('Died', 'Died')], max_length=30),
        ),
    ]
