# Generated by Django 3.2.21 on 2023-11-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine_mammal_incidents', '0004_auto_20231116_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='file_number',
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='weight_is_estimated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='age_class',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Sub-adult', 'Sub-adult'), ('Calf', 'Calf'), ('Newborn', 'Newborn'), ('Unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='condition_when_found',
            field=models.CharField(choices=[('Stage 1 = alive', 'Stage 1 = alive'), ('Stage 2 = fresh dead', 'Stage 2 = fresh dead'), ('Stage 3 = mild decomposition', 'Stage 3 = mild decomposition'), ('Stage 4 = advanced decomposition', 'Stage 4 = advanced decomposition'), ('Stage 5 = mummified/skeletal', 'Stage 5 = mummified/skeletal')], max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='length',
            field=models.DecimalField(decimal_places=2, help_text='in centimeters', max_digits=3),
        ),
    ]
