# Generated by Django 3.2.21 on 2023-11-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine_mammal_incidents', '0006_auto_20231127_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='species_confirmed_genetically',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='condition_when_found',
            field=models.CharField(choices=[('Stage 1 = alive', 'Stage 1 = alive'), ('Stage 2 = fresh dead', 'Stage 2 = fresh dead'), ('Stage 3 = mild decomposition', 'Stage 3 = mild decomposition'), ('Stage 4 = advanced decomposition', 'Stage 4 = advanced decomposition'), ('Stage 5 = mummified/skeletal', 'Stage 5 = mummified/skeletal'), ('Unknown', 'Unknown')], max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in centimeters', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='mass_incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='outcome',
            field=models.CharField(choices=[('Euthanased', 'Euthanased'), ('Restranded and euthanased', 'Restranded and euthanased'), ('Refloated, fate unknown', 'Refloated, fate unknown'), ('Died', 'Died'), ('Unknown', 'Unknown')], max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in kilograms', max_digits=10, null=True),
        ),
    ]
