# Generated by Django 4.2.15 on 2025-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine_mammal_incidents', '0007_auto_20231129_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='DBCA_staff_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='carcass_location_fate',
            field=models.CharField(blank=True, help_text='Carcass transported to or disposed of site', max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Stranding', 'Stranding'), ('Entanglement', 'Entanglement'), ('Entrapment', 'Entrapment'), ('Vessel collision', 'Vessel collision'), ('Unusual mortality event', 'Unusual mortality event'), ('Hauled-out', 'Hauled-out (for pinnipeds)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photos_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='post_mortem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='samples_taken',
            field=models.BooleanField(default=False),
        ),
    ]
