# Generated by Django 4.2.15 on 2025-07-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine_mammal_incidents', '0008_alter_incident_dbca_staff_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='entanglement_gear',
            field=models.CharField(blank=True, choices=[('Fishing net', 'Fishing net'), ('Rock lobster pot/rope', 'Rock lobster pot/rope'), ('Crab pot/rope', 'Crab pot/rope'), ('Unknown origin set gear (pot/rope)', 'Unknown origin set gear (pot/rope)'), ('Rope', 'Rope'), ('Monofilament fishing line', 'Monofilament fishing line'), ('Professional longline', 'Professional longline'), ('Braided line', 'Braided line'), ('Aquaculture infrastructure', 'Aquaculture infrastructure'), ('Tackle', 'Tackle'), ('Plastic debris', 'Plastic debris'), ('Octopus gear', 'Octopus gear'), ('Other (see comments)', 'Other (add in comments)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
