# Generated by Django 4.2.15 on 2026-02-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine_mammal_incidents', '0009_alter_incident_entanglement_gear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='age_class',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Sub-adult', 'Sub-adult'), ('Calf', 'Calf'), ('Newborn', 'Newborn'), ('Pup', 'Pup'), ('Unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='entanglement_gear',
            field=models.CharField(blank=True, choices=[('Fishing net', 'Fishing net'), ('Rock lobster pot/rope', 'Rock lobster pot/rope'), ('Crab pot/rope', 'Crab pot/rope'), ('Unknown origin set gear (pot/rope)', 'Unknown origin set gear (pot/rope)'), ('Rope', 'Rope'), ('Monofilament fishing line', 'Monofilament fishing line'), ('Professional longline', 'Professional longline'), ('Braided line', 'Braided line'), ('Aquaculture infrastructure', 'Aquaculture infrastructure'), ('Tackle', 'Tackle'), ('Plastic debris', 'Plastic debris'), ('Octopus gear', 'Octopus gear'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='outcome',
            field=models.CharField(choices=[('Euthanased', 'Euthanased'), ('Restranded and euthanased', 'Restranded and euthanased'), ('Refloated, fate unknown', 'Refloated, fate unknown'), ('Died', 'Died'), ('Recovered', 'Recovered'), ('Released', 'Released'), ('Alive', 'Alive'), ('Unknown', 'Unknown')], max_length=30),
        ),
    ]
