apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtles-deployment
  labels:
    app: turtles-deployment
spec:
  selector:
    matchLabels:
      app: turtles-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: turtles-deployment
    spec:
      containers:
        - name: turtles
          image: ghcr.io/dbca-wa/wastd
          imagePullPolicy: Always
          env:
            - name: ALLOWED_HOSTS
              value: '.dbca.wa.gov.au'
            - name: CSRF_TRUSTED_ORIGINS
              value: 'https://*.dbca.wa.gov.au'
            - name: EMAIL_HOST
              value: 'smtp.lan.fyi'
            - name: TZ
              value: 'Australia/Perth'
          resources:
            requests:
              memory: '100Mi'
              cpu: '5m'
            limits:
              memory: '2Gi'
              cpu: '1000m'
          startupProbe:
            httpGet:
              path: /livez
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      automountServiceAccountToken: false
