name: 'Run unit tests'

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgis://postgres:postgres@localhost:5432/postgres
      LOCAL_MEDIA_STORAGE: true
    permissions:
      contents: read
    services:
      postgres:
        image: postgis/postgis:16-3.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      #----------------------------------------------
      # Install GDAL into the environment
      #----------------------------------------------
      - name: Install GDAL
        id: install-gdal
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes gdal-bin libgdal-dev
      #----------------------------------------------
      # Checkout repo
      #----------------------------------------------
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        id: checkout-repo
        with:
          fetch-depth: 0
      #----------------------------------------------
      # Install & configure uv
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: '3.13'
          enable-cache: true
      #----------------------------------------------
      # Install project dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: uv sync
      #----------------------------------------------
      # Run unit tests
      #----------------------------------------------
      - name: Run tests
        run: |
          uv run python manage.py collectstatic
          uv run python manage.py migrate
          # NOTE: we can't run tests in parallel, because setup() may break DB constraints.
          uv run python manage.py test --noinput --failfast --verbosity 0 --settings wastd.test-settings
